### ISSUE TITLE
Upgrade TI MSP430 tool chain with TI official

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#110]
* http://e2e.ti.com/blogs_/b/msp430blog/archive/2015/03/05/exploring-the-msp430-tool-chain-part-5-new-msp430-standalone-gcc-now-available?DCMP=mcugen&HQS=ep-mcu-msp-msptools-twit-mspblog-20150305-en
* http://software-dl.ti.com/msp430/msp430_public_sw/mcu/msp430/MSPGCC/latest/index_FDS.html

**Comment by valeros** [comment]
Obsolate
