### ISSUE TITLE
Add library dependencies to platformio.ini

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio#134]
The file platformio.inialready contains information on the framework required to build a project. If it is missing, platformio offers to automatically install it. However, if the same project requires a library already known to the platformio library manager, the following manual steps are necessary:
1. Build using "platformio run" and examine output for missing library
2. Perform library ID search using "platformio lib search"
3. Use "platformio lib install ID" to install library
4. Repeat from step 1

I propose adding a new statement to platformio.ini that allow to specify required libraries in the form

require-libs = ID1 [, ID2 [, ..]]

instructing platformio to check if one or more of the required libs are missing and if so, suggest to automatically install them before proceeding the build.

**Comment by pelikhan** [comment]
Yes, declaring library depedencies is a great feature in npm.

Sent from my Windows Phone
________________________________

**Comment by ivankravets** [comment]
I don't have any objections :) How about to name this option like ``deplibs``?

**Comment by gandy92** [comment]
Sounds good to me :smiley:
