### ISSUE TITLE
Arduino with #include <SD.h> gives error because Energia.h is needed

### ISSUE THREAD

**Issue by Ekran** [platformio/platformio#136]
I use the simple blink example on an nano and add the line #include <SD.h>. The compiler gives the error:

.pioenvs\autogen_nanoatmega328\SD_ID79\utility\Sd2Card.cpp:21:21: fatal error: Energia.h: No such file or directory

Shouldn't it use something like arduino.h?

**Comment by ivankravets** [comment]
This library doesn't support framework ``arduino``. In other words, this is a port of this library https://github.com/adafruit/SD

I will add support for valid Arduino SD library as soon as possible.

--------

Current solution: just create in ``src`` dir file named ``Energia.h`` with the next contents:
```c
#include <Arduino.h>
```

**Comment by ivankravets** [comment]
I've just added new library which is compatible with Arduino framework. Please use it http://platformio.org/#!/lib/show/161/SD
