### ISSUE TITLE
teensy31 stops execution when using float

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio#162]
porting my avr arduino firmware to teensy 3.1 using arm4, I encountered a strange problem. 

The code compiles and uploads perfectly, but execution stops at the first point a float variable is used. Assigning a value to a float variable seems not to be the problem (maybe the code is removed during optimization?) but a multiplication already makes the arm stop dead.

has anyone seen this before and know how to fix this? I can do integer operations for now but eventually I need to use libraries that make internal use of floating point arithmetics.

thanks, Andy.

**Comment by ivankravets** [comment]
@gandy92 I've just remove hard FPU. Please [upgrade PlatformIO](http://docs.platformio.org/en/latest/installation.html#development-version) to the latest ``develop`` and update all platforms via ``> platformio update``.

Did it help you?

**Comment by gandy92** [comment]
That was fast :smile: 

Thank you for fixing this, everything works like a charme, now.

**Comment by ivankravets** [comment]
The issues from @gandy92 should be fixed as soon as possible :blush:
