### ISSUE TITLE
Allow to add more boards to existing platformio.ini

### ISSUE THREAD

**Issue by gandy92** [platformio/platformio#167]
In a fresh directory, `platformio init --board A --boardB` will create `platformio.ini` with environments for board A and board B. If the file `platformio.ini` already exists, we get an error:
```
Error: Project is already initialized. Process it with `platformio run` command
```

During development of a new project, it may be necessary, to add new environments supporting different boards. In that case, the user has to fill in all required fields manually, wihtout the benefit of the mechanims used with `init` command.

IMHO, it would be more user-friendly to provide a new command or extend the `init` command so that the user can add further boards to the `platformio.ini`.

**Comment by ajford** [comment]
I agree with this. I ended up copy/pasting the existing entry and changing manually, but it would be nice if it was possible to do this via the interface.
