### ISSUE TITLE
Autoupdates render platform unbuildable with latest published version

### ISSUE THREAD

**Issue by iterati** [platformio/platformio#171]
I did not realize that the default settings for platformio were to auto-update libraries and platforms and after a number of successful builds, an update happened that broke my build. The fix involved removing the platformio distribution I downloaded from the site, grabbing the source from github, and building/installing from the source.

I believe the problem was that updates to the teensy platform libraries were not compatible with the 1.3.0 build. Even after multiple attempts, platformio upgrade would return that it was at the most up to date version.

Here's the error my build would throw on 1.3.0:
```.pioenvs/autogen_teensy31/libFrameworkArduino.a(mk20dx128.o): In function `ResetHandler':
.../.pioenvs/autogen_teensy31/FrameworkArduino/mk20dx128.c:764: undefined reference to `__rtc_localtime'```

The project again builds successfully on 1.4.0.dev2. I recommend turning off the platform and library auto-updates by default.

**Comment by ivankravets** [comment]
Thanks a lot! Autoupdates will be disabled in PlatformIO 2.0. See my latest commit b52ff11.

**Comment by iterati** [comment]
Awesome. Thanks for your attention on this and your work on this project. It's really streamlined my development workflow.
