### ISSUE TITLE
creating copies of source files

### ISSUE THREAD

**Issue by gorsat** [platformio/platformio#177]
When I build (run) it looks like platformio is creating copies of my source files under .pioenvs\autogen_nrf51_dk\src and then compiling those copies instead of simply compiling the originals. I'm using an IDE (e.g. Eclipse) so the "show error in editor" feature opens up the platformio copy of the source file rather than showing me the error in the original. It's not obvious that the editor is showing a copy of the file (file name is the same, contents are the same) and so it's easy to accidentally make a change in the copy. Of course, that change will have no effect on the next build results and, even worse, the changes will be overwritten when platformio once again copies the original source file. Because of these kinds of problems, creating copies of the source files seems to be, in general, an inadvisable approach. So why is platformio making copies of the sources? Does it really need to do that? Why doesn't it just compile them in place? Have I just configured it wrong?

(btw, platformio is a fantastic idea. if you can add a bit more in terms of automatic IDE integration and a few more details then you'll have an absolute winner.)

**Comment by ivankravets** [comment]
Thanks for the report. I've just fixed it and will release in [PlatformIO 2.0](https://github.com/platformio/platformio/issues/159).

If you want to try PlatformIO 2.0 now, then run the simple commands:
```shell
pip uninstall platformio
pip install https://github.com/platformio/platformio/archive/feature/platformio_20.zip
```

P.S: Don't forget to use ``--force/-f`` option before each PlatformIO command if you are going to use within IDE. For example, ``platformio --force run``. See #152.

Please report if it works for you now.
