### ISSUE TITLE
Nucleo F411RE not running code correctly

### ISSUE THREAD

**Issue by dave93cab** [platformio/platformio#185]
I have a nucleo F411RE, I have tried compiling/downloading files such as blink and my own code but the code does not appear to run correctly. Printf's only transmit first character and while(1) loop does not appear to be executed. Same programs compile and run fine with mbed online compiler.

Repeated on multiple computers with same results. compile/download to freescale freedom board works correctly on both computers.

Can submit .bin generated by mbed and platformio if required, to compare?

Thanks

**Comment by valeros** [comment]
Looks like mbed fixed this issue in new version. Can you test this firmware.bin with your board?
http://drp.io/f/Q11RtNlT

**Comment by dave93cab** [comment]
Hi, 

I can try this later. I have the M10 firmware which is the latest from the mbed developer site. Do you mind posting the link to the fixed issue?

**Comment by dave93cab** [comment]
Just loaded the .bin file. If it was the blink example it didn't work, LED1 is steady. I tried it on 2 different boards with the same result. Let me know if you need anything to help diagnose the issue.

**Comment by valeros** [comment]
Yes, it's blink example. Could you please test this version:
http://drp.io/f/XyVcTlGp

**Comment by dave93cab** [comment]
Hi valeros, I just tried that one and same result I'm afraid: the LED doesn't blink.

Dave

**Comment by valeros** [comment]
Hi @dave93cab !
Could you try this version, please?
http://bit.ly/1E8TxDA

**Comment by dave93cab** [comment]
Valeros, that one worked great! Did you find the issue?

Thanks
Dave

**Comment by valeros** [comment]
I almost got it.
Could you try firmwares from this archive, please?
http://bit.ly/1bsqLGQ
It will help me clarify the problem. Thanks!

**Comment by dave93cab** [comment]
None of those worked

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platformio/commit/4ce09f1d4330f9da482c8111ce6451d14f2b081a

**Comment by dave93cab** [comment]
Great, I will give this another go later :)

**Comment by ivankravets** [comment]
I'm going to release 1.5.0 within 1 hour. Please upgrade your current version of PlatformIO to stable and retest. 

Thanks in advance!
