### ISSUE TITLE
Add Armstrap variations as available boards

### ISSUE THREAD

**Issue by beriberikix** [platformio/platformio#204]
I'm not sure if there is an automated process to upload boards to the central repository, but it would be great to have the @armstrap on there (as specified in https://github.com/platformio/platformio/issues/175#issuecomment-94838565.) Note that there are [3 variations](http://docs.armstrap.org/en/latest/hardware-overview.html#armstrap-eagle) of with differently-sized on-chip memory.

**Comment by ivankravets** [comment]
You can try new boards with PlatformIO 2.0a1 using http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by beriberikix** [comment]
I got this working with the stable 2.0. However, I still needed to include an upload.gdb and add the gdb protocol to the `.ini.` Is that as expected?

https://github.com/beriberikix/armstrap-gcc-barebones/commit/9648df3e1ac9bbe45b7d1ba14c2306c3f23ba03d

**Comment by ivankravets** [comment]
Yes, it's normal behavior of PlatformIO. This approach allows you to make own GDB commands list. 

With best regards, Ivan Kravets
- "Creative comes from talent, and never from knowledge" (c)
_________________________
http://www.ikravets.com
