### ISSUE TITLE
Missing include folder in Eclipse IDE?

### ISSUE THREAD

**Issue by madhead** [platformio/platformio#210]
First of all, I want to say thank you for this awesome project. I came from Java and using Eclipse is much more convenient for me then Arduino IDE.

I'm using platformio to program my Arduino Uno, so, I generate project with `platformio init --ide eclipse --board uno`. In this case default "include path" in Eclipse contains two platform-specific directories:

+ `/home/madhead/.platformio/packages/framework-arduinoavr/variants/standard`
+ `/home/madhead/.platformio/packages/framework-arduinoavr/cores/arduino`

With this configuration Eclipse does not know about some AVR types, like `uint8_t`. So when I use `pinMode` or `digitalWrite` I got error highlights, but the build is actually fine. This type is defined in `<stdint.h>` in AVR.

I solve this problem by manually including one more directory: `/home/madhead/.platformio/packages/toolchain-atmelavr/avr/include` to the `Includes` (`Project properties` → `C/C++ General` → `Paths and Symbols`):

![image](https://cloud.githubusercontent.com/assets/577360/7784306/d53df212-0169-11e5-9d62-e3066136cda7.png)

Am I missing something, or, maybe, this directory can be included in Eclipse projects by default?

**Comment by ivankravets** [comment]
Thanks a lot for the feedback! :+1: 

Yes, this is bug or maybe, missed feature. I will add ``includes`` from toolchains to exported paths in 2.0.1 release.
