### ISSUE TITLE
Using C++ with the STM32F4 Discovery causes linker errors, what am I doing wrong?

### ISSUE THREAD

**Issue by apvanzanten** [platformio/platformio#211]
I've created a project using the **platformio init --board=disco_f407vg** command, and then proceeded to write a main.cpp. Everything seemed to work fine at first but when I try to use **new** or **delete** I get linker errors. Specifically I have a line **int * testInt = new int;** which then causes **main.cpp:12: undefined reference to `operator new(unsigned int)'** (where line 12 is the line containing the new call).

I'm guessing I still have to add some setting to the platform.ini to configure it for full C++ support, but I can't find anything about such a setting in the documentation. What am I missing?

Thanks for the help (also thanks for building this software, I don't think I've ever had a toolchain and bsp install this quickly and easily!)

**Comment by valeros** [comment]
Hello @apvanzanten.

I have updated ldscript for stm32f4, so now you can use PlatformIO develop branch or stable 2.0.0 with this `platformio.ini:`
```
[env:disco_f407vg]
platform = ststm32
framework = cmsis
board = disco_f407vg
build_flags = -lstdc++ -lnosys
```

**Comment by apvanzanten** [comment]
Sweet, thanks for the quick fix! :+1:
