### ISSUE TITLE
C/C++ std libs no more resolved by Eclipse IDE

### ISSUE THREAD

**Issue by ncolomer** [platformio/platformio#220]
The standard C/C++ libraries include are no more resolved by Eclipse CDT IDE after initializing the project with `platformio init --ide eclipse` (eg. `stdarg.h`, `stdbool.h` or `stddef.h`). 

It seems to be a regression since I did not face the problem when settings the project configuration manually according to @ivankravets [blog post](http://www.ikravets.com/computer-life/programming/2014/06/20/building-and-debugging-atmel-avr-arduino-based-project-using-eclipse-ideplatformio), cf image below:

![screenshot](https://dl.dropboxusercontent.com/u/22884360/screenshot.png)

Maybe this is just about a missing flag/path but I saw nothing missing after comparing configs.

**Comment by ivankravets** [comment]
Thanks again for the report :+1: . Please try the latest build http://docs.platformio.org/en/latest/installation.html#development-version

Did it help you?

**Comment by ncolomer** [comment]
Hi @ivankravets, a9a9545 fixed the issue, thanks!
