### ISSUE TITLE
Hard-to-read colors in console on Winows

### ISSUE THREAD

**Issue by divanchykhin** [platformio/platformio#234]
More particularly, using cmd.exe on Windows 7 the following colors appeared: 
![cmd](https://cloud.githubusercontent.com/assets/10775884/8107716/1f791728-1054-11e5-8f92-af7dbe410e9e.png)
(this might or might not be a problem specific to a particular installation)

**Comment by ngollon** [comment]
The dark red is especially bad. 

It helps  a little to set your console's background to white and text color to black in the console's properties.

**Comment by ivankravets** [comment]
This issue isn't linked with PlatformIO. You should customise your Terminal. It uses "grayed" colors scheme by default. Click on the `Terminal icon(left top corner of window) -> Properties -> Colors -> Screen Text` and set to "white" (255,255,255). See
![screen shot 2015-09-04 at 22 08 29](https://cloud.githubusercontent.com/assets/1760209/9692471/fa6fc648-5351-11e5-99bf-9c613f837bae.png)
