### ISSUE TITLE
IDE generator only generates project file based on last env in existing platformio.ini file, ignoring `--board`

### ISSUE THREAD

**Issue by pastcompute** [platformio/platformio#242]
When I run the following command as suggested by the tutorial:
```
platformio init --ide qtcreator --board esp01
```
and the `platformio.ini` file in the directory contains a second `env:teensylc` section after the `env:esp01` section, the generator ignored the `--board esp01` option and always generates a teensylc-based qtcreator project.

I had a browse through the code and noted in `projectgenerator.py` it scans through the ini file and populates a map in function `get_project_env()` and this seems to take no notice of the `ide` selection;  for any number of `env` sections they will keep getting replaced (thus the choice of the last in the file)
I guess a fix would involve reworking how that method gets called, maybe a second loop in generate() over boards, but my head is not in Python mode at the moment

**Comment by ivankravets** [comment]
Thanks, I'll fix it in 2.2.0 release.

**Comment by ivankravets** [comment]
Please re-test it using [development version](http://docs.platformio.org/en/latest/installation.html#development-version).
