### ISSUE TITLE
Generated QtCreator project contains hard-coded paths to $HOME/.platformio directory

### ISSUE THREAD

**Issue by pastcompute** [platformio/platformio#243]
The project file generated by running `platformio init --ide qtcreator` uses absolute paths to the platformio installed SDKs for `INCLUDE` paths, etc.

For example:
`INCLUDEPATH += "/home/pastcompute/.platformio/packages/framework-arduinoespressif/variants/generic"`
This makes it unsuitable for adding to version control.
It would be prefereable if these options were instead added like:
`INCLUDEPATH += "${HOME}/.platformio/packages/framework-arduinoespressif/variants/generic"`
making the project portable between users

**Comment by ivankravets** [comment]
Please re-test it using [development version](http://docs.platformio.org/en/latest/installation.html#development-version).

Does it work for you?

**Comment by pastcompute** [comment]
Hi, I just tested this and it works. Thanks!
