### ISSUE TITLE
Version of BOSSA tool on Raspberry Pi

### ISSUE THREAD

**Issue by eliasse** [platformio/platformio#251]
Hi, 

The version of the BOSSA tool that comes with PlatformIO is 1.2, which doesn't seem to support
the Arduino framework. I had to download and compile the BOSSA fork that is targeted at Arduino
SAM platforms to be able to upload my sketch to the board https://github.com/femtoio/BOSSA.

Regards,
Elias

**Comment by ivankravets** [comment]
@valeros Please update all ``BOSSA`` packages to the latest 1.5 version. Thanks.

**Comment by valeros** [comment]
Done.

**Comment by valeros** [comment]
Done.
