### ISSUE TITLE
Update Energia related frameworks to version 17

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#259]
Need to update:
- [x] framework-energiamsp430
- [x] framework-energiativa

Check if we need to update toolchains or upload tools.

**Comment by jasiek** [comment]
Hey,

Do you guys plan to bump up Energia to v17?

**Comment by ivankravets** [comment]
@valeros please update Energia framework

**Comment by valeros** [comment]
Updated!

**Comment by jasiek** [comment]
:+1:
