### ISSUE TITLE
Cross compiler for desktop platforms

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#263]
This isn't a secret that PlatformIO initially was intended to be cross compiling tool for multiple development platforms, not just embedded.

According to the latest issues #258 and #262 I understand that this feature for desktop platforms could be interested for the developers. 

# `native` development platform

Create new `native` development platform which will use host OS's `gcc` compiler. If it doesn't exist (like on Windows), PlatformIO will install own pre-built package with `gcc` for Windows. For Mac OS X, Linux - need to show "HELP NOTICE" how `gcc` can be installed using OS's packages manager (`brew`, `apt`, `yum`, etc.)

# Desktop cross-compiling

Create new desktop based platforms:

* `windows_x86`
* `windows_amd64`
* `linux_i686`
* `linux_x86_64`
* `darwin_i386`
* `darwin_x86_64`
* `linux_arm`

These platforms could be used for cross compiling between desktop platforms. For example, host is Mac OS, then this `platformio.ini` should prepare binaries (executable files) for targets:
```ini
[env:win32]
platform = windows_x86

[env:mac64]
platform = darwin_x86_64

[env:lin32]
platform = linux_i686
```

What do you think about it?

**Comment by WillemMali** [comment]
I've been thinking about it myself, seems like a great idea. +1!

**Comment by ivankravets** [comment]
@WillemMali which is your host OS?

**Comment by WillemMali** [comment]
I'm on Windows (8.1 x64, for entertainment) and Linux (Debian stable x64,  for work). I also regularly work with Raspberry Pi's.

**Comment by ivankravets** [comment]
@WillemMali you can try the latest build. It has support for cross-compiling to windows x86 from Mac OS X, Linux 32/64

**Comment by Automatischa** [comment]
Biggest security hole once again but must be a relief to non talented coders and starters

**Comment by ivankravets** [comment]
Dear talented @Automatischa,

Please explain us about "Biggest security hole once again".

Thanks in advance!

**Comment by Automatischa** [comment]
Its only pushing open source once again

**Comment by Automatischa** [comment]
There are no rules at all just like everywhere but when i think twice its good like that ;-)

**Comment by ivankravets** [comment]
@Automatischa  Thanks, it seems that we speak using different languages. 

Have a nice weekend! :+1:

**Comment by Automatischa** [comment]
Rules, not able to delete posts? Bs
