### ISSUE TITLE
Compile Arduino with C++11

### ISSUE THREAD

**Issue by efatsi** [platformio/platformio#267]
Is it possible with the current platformio to compile Arduino projects with support for C++11? I believe it should be as easy as adding a `-std=gnu++11` flag to the cpp compile step. ([reference](http://stackoverflow.com/questions/16224746/how-to-use-c11-to-program-the-arduino))

**Comment by ivankravets** [comment]
Have you tried [build_flags](http://docs.platformio.org/en/latest/projectconf.html#projectconf-build-flags) option?

**Comment by efatsi** [comment]
Ah sorry, should have checked the docs more closely. Thanks.

**Comment by ivankravets** [comment]
Sorry for the off-top: Could I ask you to look into https://github.com/vigetlabs/platomformio/pull/2 and release new version of Atom package with all changes?

Thanks in advance!

**Comment by efatsi** [comment]
merged and pushed

**Comment by ivankravets** [comment]
Could you add description for the repo and URL to Atom's site? See my fork: https://github.com/platformio/platomformio

Like this (top, under number of commits):
```
Integration Atom IDE with PlatformIO https://atom.io/packages/platomformio  — Edit
```
