### ISSUE TITLE
can't upload to TeensyLC

### ISSUE THREAD

**Issue by altafferw** [platformio/platformio#268]
unable to upload to TeensyLC:
-------------
Found HalfKay Bootloader
error writing to Teensy
scons: *** [upload] Error 1
-------------

Simple fix, pull latest [PJRC command line loader] code from:  https://github.com/PaulStoffregen/teensy_loader_cli

**Comment by ivankravets** [comment]
Which is type of your host OS?

**Comment by altafferw** [comment]
Greetings,

> Which is type of your host OS?

- Debian 8.0 Linux, 64 bit, quad core
- Python 2.7.10

uname -a => Linux 4.1.0-1-amd64 #1 SMP Debian 4.1.3-1 (2015-08-03)
x86_64 GNU/Linux


Also have Arduino 1.6.5 w/Teensyduino 1.24 installed.


Later,
	William Altaffer
	altafferw@gmail.com

**Comment by ivankravets** [comment]
Please update PlatformIO packages:
```shell
platformio update
```

Has it helped you?

**Comment by altafferw** [comment]
Greetings,

> Please update PlatformIO packages:
> platformio update
> 
> Has it helped you?

That fixed it.  Looks like you (or I?) can close "issue #268".


Thanks,
	William Altaffer
	altafferw@gmail.com

**Comment by ivankravets** [comment]
Thanks @valeros for updates!
Thanks @altafferw for report! :beers:
