### ISSUE TITLE
install fails when using Develop.zip 

### ISSUE THREAD

**Issue by gslender** [platformio/platformio#274]
When installing from scratch using the 
`$ pip install https://github.com/platformio/platformio/archive/develop.zip`

You get this error when calling platform run
```
Error: The PlatformIO and `scons` aren't installed properly. Please use official installation manual:
http://docs.platformio.org/en/latest/installation.html
```

This was on OS X fresh install

**Comment by gslender** [comment]
Solved the problem by executing `pip install --egg scons`

**Comment by ivankravets** [comment]
Thanks for your reports!!! I've just significantly simplified installation process of PlatformIO. See http://docs.platformio.org/en/latest/installation.html#python-package-manager

Is this page clear now? Don't forget that you can directly edit https://github.com/platformio/platformio/blob/develop/docs/installation.rst and make pull-request. I'll merge your changes.
