### ISSUE TITLE
#include <limits.h> missing from Eclipse includes

### ISSUE THREAD

**Issue by gslender** [platformio/platformio#277]
As per issue title, the IDE integration fails to include .platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.8.1/include-fixed

The following is included... .platformio/packages/toolchain-atmelavr/lib/gcc/avr/4.8.1/include

but the fixed stuff isn't ?!??

**Comment by ivankravets** [comment]
Thanks. Try it http://docs.platformio.org/en/latest/installation.html#development-version
