### ISSUE TITLE
Use teensy CLI loader for upload of .hex files on OSX

### ISSUE THREAD

**Issue by heyer2** [platformio/platformio#306]
At present platformIO uses the teensy GUI for the final upload of .hex files.
A more streamlined solution might be the command line loader available at:
https://www.pjrc.com/teensy/loader_cli.html

**Comment by ivankravets** [comment]
We use CLI for Linux. Could you provide binaries for Mac OS X? I have discussion with @PaulStoffregen a few month before, he told me that there no support for Mac OS X yet.

**Comment by PaulStoffregen** [comment]
Mac support was recently contributed.
https://github.com/PaulStoffregen/teensy_loader_cli/pull/12

You still have the compile the code to get a Mac executable.

**Comment by heyer2** [comment]
I made a binary. I'm afraid I don't have my teensy nearby, but the program seems to work fine.
https://www.dropbox.com/s/l5850ic5umcb862/teensy_loader_cli?dl=0

**Comment by ivankravets** [comment]
Thanks @heyer2! `tool-teensy` package has been updated. Try it:
```
platformio update
```

P.S: I retested it with my Teensy 3.1/Mac OS X and it works! :+1:

**Comment by ivankravets** [comment]
@PaulStoffregen could we ask you to add link to http://platformio.org on these pages:

* https://www.pjrc.com/teensy/gcc.html
* https://www.pjrc.com/teensy/loader_cli.html

Thanks a lot!

**Comment by heyer2** [comment]
I can confirm it works on my end too.

**Comment by PaulStoffregen** [comment]
@ivankravets 
I've added a "PlatformIO Integration" section.
https://www.pjrc.com/teensy/loader_cli.html
Can you recommend text to replace the "TODO" line?

**Comment by ivankravets** [comment]
[PlatformIO](http://platformio.org) is a cross-platform code builder and the missing library manager (Ready for embedded development, IDE and Continuous Integration).

* [Install PlatformIO](http://platformio.org/#!/get-started)
* Print supported Teensy boards
```shell
platformio boards teensy
```
* [Initialise new project](http://docs.platformio.org/en/latest/userguide/cmd_init.html) with pre-configured settings for the specified board (for example, Teensy 3.1)
```shell
platformio init --board teensy31
````
* Put source code files to newly created `src` directory, build firmware and upload it
```shell
platformio run --target upload
```

Also, see examples of pre-configured Teensy projects:
* [HID USB Mouse](https://github.com/platformio/platformio/tree/develop/examples/teensy/teensy-hid-usb-mouse)
* [Chat Server with built-in library](https://github.com/platformio/platformio/tree/develop/examples/teensy/teensy-internal-libs)
* [MBED Blink](https://github.com/platformio/platformio/tree/develop/examples/mbed/mbed-blink)

**Comment by ivankravets** [comment]
Dear @PaulStoffregen,

See my post above https://github.com/platformio/platformio/issues/306#issuecomment-148033650

You can modify it if you want.

Thanks in advance! :+1:  :beers:
