### ISSUE TITLE
ESP-12E (nodeMCU) support?

### ISSUE THREAD

**Issue by grzegorzshub** [platformio/platformio#310]
Hi
Any chance for nodeMCU support please?
Thank you

**Comment by ivankravets** [comment]
Try this manual http://clemix.de/www/platformio

**Comment by grzegorzshub** [comment]
Hello
Thank you for prompt answer.
I use Atom with platform on Mac. Does it mean that I can use -board esp01 for nodeMCU?
I’m a bit confused. That what I have tried but got some issues. The same code worked fine via Arduino IDE.
Thank you
Best
Grzegorz

**Comment by ivankravets** [comment]
Hi @grzegorzshub,

Paste here source code which doesn't work with @PlatformIO.

Thanks.

**Comment by grzegorzshub** [comment]
Hi Ivan
I’m trying to recreate the issue and get back to you with more details soon.
Thank you
Best
Grzegorz

**Comment by grzegorzshub** [comment]
It looks like it is a Adafruit_NeoPixel library issue.
Code compiles with Atom+platformio without any warnings or errors, neopixel doesn’t work. Neopixel works fine when the same code is compiled with Arduino IDE.
The code:

#include <ESP8266WiFi.h>
#include <Adafruit_NeoPixel.h>

#define neoPin 14  //neopixel on nodeMCU pin D5
#define NUMPIXELS      1  // How many NeoPixels are attached to the Arduino?
Adafruit_NeoPixel pixels = Adafruit_NeoPixel(NUMPIXELS, neoPin, NEO_GRB + NEO_KHZ800);

void setup() {

pixels.begin();
pixels.setPixelColor(0, pixels.Color(255, 0, 0));
pixels.setBrightness(20);
pixels.show();
}

void loop() {
}

**Comment by valeros** [comment]
Hi @grzegorzshub !
I've just added ESP-12E board.
Please update packages via `platformio update` and install development version of PlatformIO
http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by grzegorzshub** [comment]
Hi

Tested with PlatformIO version 2.4.0.dev0 and board = esp12e and still the same issue with neopixel.
Just noticed that arduino IDE works with nodeMCU ESP12E 80Mz, while platformio —boards 40Mz, does it matter?

**Comment by ivankravets** [comment]
@grzegorzshub you can force MCU speed manually via http://docs.platformio.org/en/latest/projectconf.html#board-f-cpu

**Comment by grzegorzshub** [comment]
neopixel library works fine with board_f_cpu = 80000000L
Thank you!
