### ISSUE TITLE
upload_port is not honored without a framework specified

### ISSUE THREAD

**Issue by countrodrigo** [platformio/platformio#313]
The `upload_port` environment option doesn't seem to be honored when not using a framework. Here is my platform.ini:

```
[env:arduino_pro5v]
platform = atmelavr

#framework = arduino
#board = uno

board_mcu = atmega328
board_f_cpu = 16000000L

upload_protocol = arduino
upload_port = /dev/cu.usbmodem1451
upload_speed = 115200

targets = upload
```

If I use the `framework` and `board` options that are commented instead of the direct settings, it works just fine.

The avrdude command it tries to run is:
`/Users/countrodrigo/.platformio/packages/tool-avrdude/avrdude" -v -p atmega328 -C "/Users/countrodrigo/.platformio/packages/tool-avrdude/avrdude.conf" -c arduino -b 115200 -D -U flash:w:.pioenvs/arduino_pro5v/firmware.hex:i`
This is missing the -P option. If I run that command manually and pass the `-P /dev/cu.usbmodem1451`, then it can program the device just fine.

**Comment by ivankravets** [comment]
Thanks for the report, I see this bug. However, this issue isn't linked with missed `framework` option, but with missed `board` option. Try to specify similar `board` to you hardware which is listed in `platformio boards`.

**Comment by ivankravets** [comment]
Please re-test it in the latest develop version http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by ivankravets** [comment]
People don't like to read documentation http://docs.platformio.org/en/latest/platforms/atmelavr.html#upload-using-programmer

**Comment by alexbonhomme** [comment]
People don't often like this kind of comments too.

The documentation isn't that obvious (as you think it is). There is some examples with the `-P` flags, others without and others with `-P` and `-b` one. There is not clear explanation saying that the `upload_port` doesn't work as expected.

I would do a PR about it. Thanks for your help.

**Comment by ivankravets** [comment]
@alexbonhomme fill free to make PR to https://github.com/platformio/platformio-docs/blob/develop/platforms/atmelavr_extra.rst
