### ISSUE TITLE
Boards: should support specifying whether .hex or .bin is needed for each board

### ISSUE THREAD

**Issue by rph8** [platformio/platformio#316]
I had the issue that the Seeed Arch BLE needs a .hex file to be copied to the MBED USB, not a .bin. Another board from Seeed, the Arch Max does need a .bin file.
So there should be a way in the board JSON language whether the board needs a .hex or .bin.

I fixed this for now in my local installation by cloning the nordicrf51 platform and changing the builder script for the second platform from
```
if "uploadlazy" in COMMAND_LINE_TARGETS:
    target_firm = join("$BUILD_DIR", "firmware.bin")
else:
    target_firm = env.ElfToBin(join("$BUILD_DIR", "firmware"), target_elf)
```
to:
```
if "uploadlazy" in COMMAND_LINE_TARGETS:
    target_firm = join("$BUILD_DIR", "firmware.hex")
else:
    target_firm = env.ElfToHex(join("$BUILD_DIR", "firmware"), target_elf)
```

(Used version 2.3.4.)

**Comment by ivankravets** [comment]
Please re-test it using the latest development version http://docs.platformio.org/en/latest/installation.html#development-version
