### ISSUE TITLE
Export/Import installed libs

### ISSUE THREAD

**Issue by maxpowel** [platformio/platformio#318]
Hello this project is great! But I miss something like 
pip freeze > requirements.txt
and
pip install -r requirements.txt

At this moment I am wiriting the dependency list in a file (a text file with all ids) and a bash script to execute all "platformio lib install ID" but would be nice if this feature could be available in platformio. I could write this functionality but I don't know if for some reason you decided to avoid it.

Thank you

**Comment by ivankravets** [comment]
How about this option? http://docs.platformio.org/en/latest/projectconf.html#lib-install

**Comment by ivankravets** [comment]
Please re-open this issue if you still have any questions.
