### ISSUE TITLE
Invalid character escape

### ISSUE THREAD

**Issue by hameno** [platformio/platformio#326]
Hi,
I'm using PlatformIO, version 2.4.0.dev2 and created a new project with the command 

    platformio init --ide clion -b uno

It created a CMakeLists file with the following entry:

    add_executable(test src\main.cpp)

It did not escape the "\" (or used "/")

Env:
Windows 10 10586.3
PlatformIO, version 2.4.0.dev2

**Comment by ivankravets** [comment]
Please re-test it within @PlatformIO 2.4.0.dev3 http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by hameno** [comment]
Looks good! :+1:
