### ISSUE TITLE
Add sources in CLion

### ISSUE THREAD

**Issue by madhead** [platformio/platformio#327]
I want to create a wrapper class to control Servo:

```cpp
# Gate.h

#ifndef PRACTICE_1_GATE_H
#define PRACTICE_1_GATE_H

#include <Arduino.h>
#include <Servo.h>

class Gate {
private:
    Servo servo;
public:
    Gate(uint8_t);

    void open();

    void close();
};

#endif //PRACTICE_1_GATE_H
```

```cpp
# Gate.cpp

#include <Arduino.h>
#include "Gate.h"

Gate::Gate(uint8_t pin) {
    servo.attach(pin);
}

void Gate::open() {
    servo.write(0);
}

void Gate::close() {
    servo.write(45);
}
```

How can I add it to the CMake project in CLion to have autocomplete and all the stuff? I've done this:

```
add_executable(practice_1 src/main.cpp src/gate)
```

in `CMakeLists.txt`, but still have some red in the editor:
![snapshot1](https://cloud.githubusercontent.com/assets/577360/11170541/8c82a856-8be8-11e5-8fe8-5da7cf4dbbb8.png)
![snapshot2](https://cloud.githubusercontent.com/assets/577360/11170542/92ffb32c-8be8-11e5-8cd4-12ccee278228.png)

**Comment by valeros** [comment]
Hi @madhead!
Have you tried to add the path to the library?
For example:
`include_directories("~/user/.platformio/packages/framework-arduinoavr/libraries/Servo/src")`

**Comment by madhead** [comment]
@valeros `Servo.h` resolves ok when in `src/main.cpp`.

**Comment by ivankravets** [comment]
@madhead where it doesn't resolve?

**Comment by madhead** [comment]
It doesn't resolve in `src/gate/Gate.h`, `src/gate/Gate.cpp`. Including these files explicitly (`add_executable(practice_1 src/main.cpp src/gate/Gate.cpp)` instead of just `add_executable(practice_1 src/main.cpp src/gate)`) solves the problem.

It's not generally a bug, it's just a "help wanted" question. I'd like to hear from more experienced people how do they use multiple source files in platformio / CLion.

Also, what how should I treat `lib` folder? Putting sources there breaks even vanilla `platformio run` with exception like "Cannot find implementation for `Gate::Gate` / `Gate::open` / `Gate::close`". I include file as `#include "../lib/Gate.h"` and looks like `Gate.cpp` is no seen at all.

**Comment by valeros** [comment]
@madhead 
Strange, I have only one file in add_executable option: `add_executable(clion src/blink.cpp)`, and autocomplete works fine in `gate.cpp`:
![clion](http://i.piccy.info/i9/47376c55f570d91a1d39c343d377a259/1447689701/15271/749110/clion.png)

**Comment by madhead** [comment]
@valeros can you please share whole your project as zip somewhere?

**Comment by valeros** [comment]
Sure, bit only for Windows:https://dl.dropboxusercontent.com/u/10025728/clion.zip

**Comment by madhead** [comment]
Got it. Thanks for the example. The trick was adding `include_directories("${HOME}/.platformio/packages/framework-arduinoavr/libraries/Servo/src")` manually.

One more question: how to correctly use `lib` folder that is generated by `platformio init`.

**Comment by ivankravets** [comment]
> One more question: how to correctly use lib folder that is generated by platformio init.

This information is located in `lib/readme.txt`, for example,  https://github.com/platformio/platformio/blob/develop/examples/wiring-blink/lib/readme.txt

**Comment by madhead** [comment]
Not sure why that didn't work for me for the first time, but now it looks ok.

Thank you guys for the help!

**Comment by ivankravets** [comment]
Thank you too that using @PlatformIO! Don't forget to follow us on [Twitter](https://twitter.com/PlatformIO_Org).
