### ISSUE TITLE
Won't compile a library that compiles without issue with Arduino IDE

### ISSUE THREAD

**Issue by al-uminium** [platformio/platformio#331]
Reproduce Steps:
======
1. `platformio init` a new project
2. Download https://github.com/mysensors/Arduino/archive/development.zip
3. Copy `libraries/*` into new project `lib` folder 
4. Copy example from zip file's `libraries\MySensors\examples\GatewaySerial\GatewaySerial.ino` into new project `src` directory
5. `platformio run`

Expected Result
======
Project compiles
Works in Arduino IDE ver 10606

Real Result
======
Project fails to compile

**Comment by valeros** [comment]
Hi @al-uminium!

Looks like MySensor library needs unusual building logic, the same as for Souliss library in #298 
Could you try to add in your `platformio.ini` next options:
```
build_flags = -I/path/to/lib/MySensors
lib_ignore = MySensors
```

**Comment by al-uminium** [comment]
YES. Good. YAY. Issue can be close.
Did I not see documentation?

**Comment by ivankravets** [comment]
Dear @al-uminium, I will add it to docs.

**Comment by ivankravets** [comment]
Added to FAQ http://docs.platformio.org/en/latest/faq.html#can-not-compile-a-library-that-compiles-without-issue-with-arduino-ide

**Comment by ivankravets** [comment]
Resolved in https://github.com/platformio/platformio/issues/289
