### ISSUE TITLE
simulAVR and gdb-avr missed in toolchain-atmelavr-linux

### ISSUE THREAD

**Issue by OmarBelkhiria** [platformio/platformio#334]
When I tried to configure external tools before debugging my .cpp code (Eclipse), I didn't find 'simulavr' and 'gdb-avr' files at this folder: ${HOME}/.platformio/packages/toolchain-atmelavr/bin/
I use Ubuntu 14.04 64-bit.

**Comment by valeros** [comment]
Hi @OmarBelkhiria 
`avr-gdb` is restored, please update packages via `platformio update`
http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by ivankravets** [comment]
@OmarBelkhiria please re-open this issue if you still have ant problems

**Comment by OmarBelkhiria** [comment]
Thank you @valeros but  'simulavr' is still not included. How to re-open the issue?

**Comment by valeros** [comment]
@OmarBelkhiria Please, update your packages via `platformio update`

**Comment by OmarBelkhiria** [comment]
@valeros it's all right now; thanks.
