### ISSUE TITLE
How to specify a custom core

### ISSUE THREAD

**Issue by foufee** [platformio/platformio#338]
I have a custom board for which I need a custom core (based on the PanStamp core), what is the best way to do this?

**Comment by ivankravets** [comment]
1. See [Custom Board](http://docs.platformio.org/en/latest/platforms/creating_board.html) doc. You can use @mplewis's code https://github.com/platformio/platformio/blob/develop/platformio/boards/punchthrough.json
2. Put your core to `~/.platformio/packages/framework-arduinoavr/cores` and specify it for board https://github.com/platformio/platformio/blob/develop/platformio/boards/punchthrough.json#L11

**Comment by ivankravets** [comment]
Don't forget that your "core" will be removed when new  `framework-arduinoavr` will be available. In this case I recommend to use symlink and keep own "core" outside @PlatformIO's packages.

**Comment by mplewis** [comment]
When we build our server container with PlatformIO included, it always starts by installing PlatformIO, then installing AtmelAVR, then copying custom cores. That way we are always sure that our core hasn't been overwritten by an update of arduinoavr framework.

**Comment by ivankravets** [comment]
@foufee please reopen this issue if you still need help
