### ISSUE TITLE
Inaccurate Vim instructions?

### ISSUE THREAD

**Issue by skorokithakis** [platformio/platformio#340]
I followed the instructions for Vim integration, but I don't see anything that would map `ctrl+b` to run the `Makefile`. Is there a binding missing to run `:make` with `ctrl+b`?

**Comment by ivankravets** [comment]
Which is your OS? `CMD+B` works good for me under MacVim

**Comment by skorokithakis** [comment]
Ubuntu Linux. I had to add `nnoremap <C-b> :make<CR>` to my `.vimrc` to get it to work, it works with that, though.

**Comment by ivankravets** [comment]
Added to docs. Thanks!
