### ISSUE TITLE
Library 92 not updating to latest

### ISSUE THREAD

**Issue by karrots** [platformio/platformio#344]
Platformio is not showing the latest commit for some libraries. Example below is one commit behind. Is this a manual update process?

```
$ platformio lib show 92
RFM69
-----
Authors: Felix Rusu https://github.com/LowPowerLab
Keywords: rf, radio, wireless, spi
Frameworks: arduino
Platforms: atmelavr
Version: bd50fa29df

RFM69 library for RFM69W, RFM69HW, RFM69CW, RFM69HCW (semtech SX1231, SX1231H)


```

**Comment by ivankravets** [comment]
Please re-create this issue in related repository https://github.com/platformio/platformio-api/issues

Thanks a lot!
