### ISSUE TITLE
serialports monitor ignores parameters (pySerial < 3)

### ISSUE THREAD

**Issue by MrSnowflake** [platformio/platformio#346]
Hi,

The options for the serial monitor are ignored when using pySerial < 3. (I use 2.7). The following command should open a serial monitor with baudrate 115200:

    platformio serialports monitor -b 115200

But it opens as 9600, which is the default value.

**Comment by MrSnowflake** [comment]
It seems to be something with the parsing of the options in serial.tools.miniterm. But I can't figure out what exactly.

**Comment by ivankravets** [comment]
Hi @MrSnowflake,

This issue is linked with the latest Click 6.0. I will fix it as soon as possible.

Temporary solution:
```
pip uninstall click
pip install "click<6"
```

**Comment by ivankravets** [comment]
Also, don't forget about :star: ( https://github.com/platformio/platformio/stargazers ) for @valeros :blush:

**Comment by ivankravets** [comment]
I've just opened related issue https://github.com/mitsuhiko/click/issues/473

If this isn't Click's bug, I'll drop Click version to "click<6".

**Comment by ivankravets** [comment]
Fixed in 2.4.0
