### ISSUE TITLE
Proper way to import mbed library

### ISSUE THREAD

**Issue by andriyadi** [platformio/platformio#361]
Hi again guys,

I wonder if there's a proper way to import or include libraries in mbed portal into platformio project, say using IDE CLion.

What I'm doing currently is "exporting to desktop IDE" program and libraries from mbed portal, and copy and paste to lib folder. It would be awesome if the `platformio lib` command is able to accommodate that, or other options.

Platformio is getting integrated deeply into my workflow. Thanks for all the efforts!

**Comment by ivankravets** [comment]
PlatformIO Library Registry contains the popular mbed libraries. See http://platformio.org/#!/lib/search?query=framework%253Ambed&page=1.

Is your library registered here?

**Comment by ivankravets** [comment]
Please reopen if you still need help.

**Comment by andriyadi** [comment]
Sorry I missed this. 
I'd like to integrate [HTTPClient-SSL libraries](https://developer.mbed.org/teams/MultiTech/code/HTTPClient-SSL/), as it seems working flawlessly with ESP8266Interface. Also [VS1053Lib](https://developer.mbed.org/users/ollie8/code/VS1053lib/) library or alike.

Please advice.

**Comment by ivankravets** [comment]
Please place these libraries to `lib` folder into your project. If them work, then we will add it to PlatformIO Library registry

**Comment by andriyadi** [comment]
HTTPClient-SSL libraries cannot be built by default, unless I change the file structure to be flat.
VS1053Lib is fine. I also managed to use this one, [VS1053b](https://developer.mbed.org/users/christi_s/code/VS1053b/)

**Comment by andriyadi** [comment]
Hi @ivankravets 
I have not seen the VS1053b library when I search using `platformio lib search`

No pressure though :)

**Comment by ivankravets** [comment]
@gandy92 could you update MBED library configs and include requested libs?

Thanks in advance!

**Comment by dh1tw** [comment]
+1 for a import of mbed Libraries. I'm currently working with the MQTT client and find it rather cumbersome to download, copy them in the lib directory and adopt the folder structure so that the dependency finder can actually find them.

**Comment by ivankravets** [comment]
@dh1tw you can pull request to https://github.com/platformio/platformio-libmirror/tree/master/configs/mbed with required library. I'll register it.

**Comment by ivankravets** [comment]
@dh1tw  
>  I'm currently working with the MQTT client and find it rather cumbersome to download, copy them in the lib directory and adopt the folder structure so that the dependency finder can actually find them.

Could you specify the link to this library?
