### ISSUE TITLE
Avoiding IDE import errors

### ISSUE THREAD

**Issue by orome** [platformio/platformio#362]
In my IDE (CLion 1.2.1) I have
```
#include <EEPROM.h>
```
which is reported by the IDE inspector as an error, along with usages of all the values it defines. Building with PlatformIO works fine (so I have this somewhere) but the IDE's file inspection can't locate it.

How do I ensure that CLion knows where to look for these headers?

**Comment by ivankravets** [comment]
1. `platformio upgrade` to the latest 2.5.0 release
2. Update your project with used libraries using `platformio init --ide clion --board ???`

See warning in documentation http://docs.platformio.org/en/latest/ide/clion.html#project-generator
> The libraries which are added, installed or used in the project after generating process wont be reflected in IDE. To fix it you need to reinitialize project using `platformio init` (repeat it).

**Comment by orome** [comment]
@ivankravets — So I need to specify the IDE and the board all over again. That seems wrong. Also, when I do that, some of the IDE settings get wiped out (e.g., window positions). Is there no way to just update eat project other than reinitializing it from scratch?

**Comment by ivankravets** [comment]
> Is there no way to just update eat project other than reinitializing it from scratch?

You can clone your project, apply `platformio ini --ide clion`, then copy `CMakeLists.txt` to original project. 

I've just opened new issue/feature for it #364

**Comment by orome** [comment]
Cool, thanks I'll watch #364.
