### ISSUE TITLE
What does the 'arduino' avrdude programmer do?

### ISSUE THREAD

**Issue by orome** [platformio/platformio#363]
PlatformIO (at least using CLion) executes 

    avrdude ... -c arduino ...

to load program the my Arduino Uno, but it's unclear to me what it's doing. All the documentation I've found refers to the value of the `-c` setting as the "programmer"; and all the documentation I can find about that term describe something that's a hardware component connected to the "ISCP header". But I'm connected over a serial port with no special hardware.

Is PlatformIO using the bootloader to program my Arduino? In that case what role does the `-c arduino` play (is it specifying the bootloader, or something that depends on how I'm connected)?

---
    avrdude -v -p atmega328p -C "~/.platformio/packages/tool-avrdude/avrdude.conf" -c arduino -b 115200 -P /dev/cu.usbmodem1421 -D -U flash:w:.pioenvs/uno/firmware.hex:i

**Comment by itsjustvenky** [comment]
This is what I see from arduino IDE

C:\Program Files (x86)\Arduino\hardware\tools\avr/bin/avrdude -CC:\Program Files (x86)\Arduino\hardware\tools\avr/etc/avrdude.conf -v -patmega328p -carduino -PCOM3 -b115200 -D -Uflash:w:C:\Users\VENKAT~1.VEN\AppData\Local\Temp\build727352015918313731.tmp/sketch_dec09a.cpp.hex:i 

Here is the documentation for avrdude : http://www.nongnu.org/avrdude/user-manual/avrdude_4.html#Option-Descriptions

**Comment by ivankravets** [comment]
@itsjustvenky thanks for the answer.

@orome you can control programmer-id/protocol using [upload_protocol](http://docs.platformio.org/en/latest/projectconf.html#upload-protocol) option.

**Comment by orome** [comment]
@itsjustvenky — So? That's the documentation I quoted in the question. For `arduino` its explanation is 	"Arduino". I was looking for a bit more than that.

@itsjustvenky — The question is simply: What does choosing `-c arduino` do? Specifically, ***is it using the bootloader***, when I'm connected to the Uno using the serial port?

**Comment by itsjustvenky** [comment]
@orome Best place to post this question is "Arduino Forums".

anyway 
"arduino" is a configuration name.

Go through this file

https://raw.githubusercontent.com/adafruit/Trinket_Arduino_Linux/1.0.5/arduino-1.0.5/hardware/tools/avrdude.conf

**Comment by orome** [comment]
@itsjustvenky — I'm a beginner. That file doesn't help much. What  "Arduino Forums" do you recommend?

**Comment by itsjustvenky** [comment]
@orome https://forum.arduino.cc/

if you find a clear answer, please do post the answer here. thanks
