### ISSUE TITLE
Question : framework-arduinoespressif upgrades ?

### ISSUE THREAD

**Issue by itsjustvenky** [platformio/platformio#370]
I see weekly there are some changes made to  "https://github.com/esp8266/Arduino/" master branch. So how often these changes get into @platformio ?

do these get released with a major release or a milestone ? let me know. thanks.

**Comment by ivankravets** [comment]
PlatformIO uses stable versions of toolchains, frameworks, etc. See https://github.com/esp8266/Arduino#available-versions

**Comment by itsjustvenky** [comment]
got it. thanks
