### ISSUE TITLE
CMSIS support for Nucleo F401RE

### ISSUE THREAD

**Issue by g7uvw** [platformio/platformio#373]
The ST Nucleo F401RE board doesn't support the CMSIS framework when using platformio 2.5 or previous versions.

[Sun Dec 13 18:50:06 2015] Processing nucleo_f401re (platform: ststm32, board: nucleo_f401re, framework: cmsis)
--------------------------------------------------------------------------------------------------------------------------------------------
Error: This board doesn't support cmsis framework!
================================ [ ERROR ] Took 0.47 seconds ============================================================

Can support please be added? I'd try myself, but I don't know where to start. I'll happily act as a beta tester.

**Comment by ivankravets** [comment]
Please upgrade to https://github.com/platformio/platformio/releases/tag/v2.6.0
