### ISSUE TITLE
section `.text` will not fit in region `iram1_0_seg`

### ISSUE THREAD

**Issue by andriyadi** [platformio/platformio#375]
I kept getting this error
```section '.text' will not fit in region 'iram1_0_seg'```

while building project for esp12e

Using the exact source code and build with Arduino IDE didn't raise that error. Please advice.

**Comment by andriyadi** [comment]
FYI. I've updated platformio to the latest version.

Used libraries:
ESP8266WiFi
DNSServer
ESP8266WebServer
EEPROM
Wire

**Comment by valeros** [comment]
Hi @andriyadi 
Can you share your project for testing?

**Comment by andriyadi** [comment]
@valeros can I share to you privately, as this is my company's project. I'm afraid I can't share the project openly. Please share your email. Thanks.

**Comment by valeros** [comment]
@andriyadi Sure, `valeros08@gmail.com`

**Comment by andriyadi** [comment]
It's sent. Thanks in advance.

**Comment by andriyadi** [comment]
Any workaround so far?

**Comment by ivankravets** [comment]
Yes, this is a bug. I'm working on it. Please wait for the new develop release today.

**Comment by ivankravets** [comment]
Please run `platformio update`. Does it work?

**Comment by ivankravets** [comment]
Please upgrade to https://github.com/platformio/platformio/releases/tag/v2.6.0

**Comment by andriyadi** [comment]
It works flawlessly!

Thanks!

**Comment by ivankravets** [comment]
Thanks you too that report this `typo` issue.
