### ISSUE TITLE
Undefined reference to main error. collect2.exe: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by Seep1959** [platformio/platformio#388]
I am trying to compile the stm32f4discovery-libopencm3 blink example and I am getting this error, [here is the terminal log](https://gist.github.com/Seep1959/66d92eedf24e8edb0086)

**Comment by valeros** [comment]
Hi @Seep1959 
Have you implemented `main` function?
I compiled this `miniblink` https://github.com/libopencm3/libopencm3-examples/blob/master/examples/stm32/f4/stm32f4-discovery/miniblink/miniblink.c without any errors.

**Comment by Seep1959** [comment]
Yes, I did. I have actually tried both the example you linked and the platformio example.

**Comment by ivankravets** [comment]
@Seep1959 please give us a star (:star:) https://github.com/platformio/platformio/stargazers for the help

**Comment by valeros** [comment]
I don't see any others files built except framework files.
Could you provide your project structure?

**Comment by Seep1959** [comment]
Okay, well I feel like a bit of an idiot now. Turns out my c file was saved as a txt file. I saved it as a proper c file and it compiled correctly.

**Comment by ivankravets** [comment]
Cool. Have a nice coding and weekend! :beer:  :smile:
