### ISSUE TITLE
Using PlatformIO with Atom || Changing between .ino files

### ISSUE THREAD

**Issue by tiferrei** [platformio/platformio#389]
Hi, I am unsure if I should ask this here or in an atom forum, but I have Platomformio installed on Atom, running perfectly, the only thing I am intrigued is if I have to init a PlatformIO project for each .ino file that I want to upload. Isn't there a way of PlatformIO only compile and Upload the file I have open on Atom?

Thank you,
Tiago Ferreira

![screen shot 2015-12-18 at 18 49 27](https://cloud.githubusercontent.com/assets/8849915/11904451/150a3f84-a5b8-11e5-94d4-1ceb9fbd5c94.png)

**Comment by ivankravets** [comment]
HI, please create 2 separate projects. PlatformIO doesn't process only SINGLE opened file, it processes all files from `src` directory. However, it uses opened file as "indicator" where need to find `src` directory.

**Comment by tiferrei** [comment]
Actually I came up with a possible solution, join all the programs as functions and just call the specific function on the void loop()

**Comment by ivankravets** [comment]
Do you need additional help?

**Comment by ivankravets** [comment]
Don't forget to give us a star :star:  https://github.com/platformio/platformio/stargazers

Thanks!

**Comment by tiferrei** [comment]
Nope! By the way I think you made a great job, I really like the idea of PlatformIO, give me any link for reviews I can give, you got another fan! ;)

**Comment by ivankravets** [comment]
Thanks for :star: https://github.com/platformio/platformio/stargazers ! Here is a list with articles about us http://docs.platformio.org/en/latest/articles.html

Don't hesitate to contact us if have any questions.

**Comment by tiferrei** [comment]
Thanks! Keep up the great work!

**Comment by ivankravets** [comment]
Where is star :star:  for us? :blush:

**Comment by tiferrei** [comment]
How do I "star"?

**Comment by ivankravets** [comment]
Thanks! It helps grow up our project!

**Comment by tiferrei** [comment]
Wish you best of luck and a Merry Christmas!

**Comment by ivankravets** [comment]
Thanks! :smile: You too! Happy Holidays! :christmas_tree:
