### ISSUE TITLE
Arduino & Engduino Serial Monitor

### ISSUE THREAD

**Issue by tiferrei** [platformio/platformio#392]
Hi, sorry if this is a stupid question but how can I see the `<Serial.println>` output?

Thanks,

Tiago Ferreira

![screen shot 2015-12-19 at 12 31 59](https://cloud.githubusercontent.com/assets/8849915/11912966/8a47ca0c-a64c-11e5-83ee-28ede64c4213.png)

**Comment by ivankravets** [comment]
Platomformio Package for Atom editor doesn't have built in serial monitor. Try to find related package in Atom packages registry. 

Nevertheless, you can use native [platformio serialports monitor](http://docs.platformio.org/en/latest/userguide/cmd_serialports.html#platformio-serialports-monitor).

**Comment by ivankravets** [comment]
If you have any questions please reopen this issue. Thanks.
