### ISSUE TITLE
installation failed on linux-x86 (ubunut 15.04)

### ISSUE THREAD

**Issue by framlin** [platformio/platformio#393]
Servus,

I tried to install platformio, but it fails with the following message:

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-pLMzk4/scons/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-EveMj1-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-pLMzk4/scons

[FAILURE]
The installation process has been FAILED!
Please report about this problem here
< https://github.com/platformio/platformio/issues >

Can anybody please give me a hint, what is going wrong?

**Comment by framlin** [comment]
Sorry, I did not "install the udev-rules ....."

**Comment by ivankravets** [comment]
Does it work for you now?

**Comment by ivankravets** [comment]
Would be grateful for the :star: https://github.com/platformio/platformio/stargazers

**Comment by framlin** [comment]
yepp, it does work now

**Comment by ivankravets** [comment]
Thanks for the report. Would be thankful for the :star: https://github.com/platformio/platformio/stargazers

Happy Holidays and Merry Christmas! :christmas_tree:
