### ISSUE TITLE
Digispark Micronucleus Upload: Not Found

### ISSUE THREAD

**Issue by peterkjacobson** [platformio/platformio#394]
I am using a Digispark board and when I upload the script does not seem to be able to locate the micronucleus program.  I have verified that micronucleus does appear in the correct folder and I can upload manually, but PlatformIO doesn't seem to be able to use it.  The error is as follows:

[Sun Dec 20 12:09:15 2015] Processing digispark-tiny (platform: atmelavr, board: digispark-tiny, framework: arduino)
--------------------------------------------------------------------------------
BeforeUpload(["upload"], [".pioenvs/digispark-tiny/firmware.hex"])
Please unplug/plug device ...
"/home/peter/.platformio/packages/tool-micronucleus/micronucleus" -c digispark --timeout 60 .pioenvs/digispark-tiny/firmware.hex
sh: 1: /home/peter/.platformio/packages/tool-micronucleus/micronucleus: not found
scons: *** [upload] Error 127
========================= [ ERROR ] Took 0.56 seconds =========================
[Finished in 0.954s]

**Comment by peterkjacobson** [comment]
Nevermind, somehow the folder was changed from "tool-micronucleus" to "tools-micronucleus."  My fault I imagine.

**Comment by ivankravets** [comment]
I've just checked you board and could not repeat this issue. Did you renamed this folder manually?

**Comment by ivankravets** [comment]
Hm... Could you remove totally `/home/peter/.platformio` folder and try build project from the scratch? 

This is important for us. Need to understand that all works good. Thanks.

**Comment by peterkjacobson** [comment]
I will try this tonight and report back to you.  Thanks for the quick response!

**Comment by ivankravets** [comment]
Thanks! I reassigned this issue to 2.6.3 release. Will wait for your report.

**Comment by ivankravets** [comment]
Please reopen this issue if need help

**Comment by peterkjacobson** [comment]
So I deleted .platformio and attempted to run, and the same issue actually appeared.  It installed micronucleus properly and I can see it in the right folder, but even if I go to that folder in terminal and run micronucleus directly it says "command not found."

Here is the output from platformio:

[Tue Dec 22 19:07:44 2015] Processing digispark-tiny (platform: atmelavr, board: digispark-tiny, framework: arduino)
--------------------------------------------------------------------------------
BeforeUpload(["upload"], [".pioenvs/digispark-tiny/firmware.hex"])
Please unplug/plug device ...
"/home/peter/.platformio/packages/tool-micronucleus/micronucleus" -c digispark --timeout 60 .pioenvs/digispark-tiny/firmware.hex
sh: 1: /home/peter/.platformio/packages/tool-micronucleus/micronucleus: not found
scons: *** [upload] Error 127
========================= [ ERROR ] Took 0.56 seconds =========================
[Finished in 0.967s]

**Comment by peterkjacobson** [comment]
If I run ./micronucleus in the directory it does work.

**Comment by ivankravets** [comment]
@peterkjacobson which is your host OS? Could you try this solution https://github.com/platformio/platformio/issues/400#issuecomment-166862334 ?

**Comment by peterkjacobson** [comment]
I will test when I get home tonight. Previously I had resolved this by
downloading and making the micronucleus file and putting it into the
folder.  I will confirm tonight.

**Comment by peterkjacobson** [comment]
I am on 64 bit Ubuntu 15.10.  Replacing the micronucleus file with a 64 bit version fixed the problem and it uploads as expected.

**Comment by valeros** [comment]
@peterkjacobson  Please, update your `tool-micronucleus` package via `platformio update`

**Comment by ivankravets** [comment]
@peterkjacobson please reopen this issue if it doesn't work.

P.S: Please give us a :star: here https://github.com/platformio/platformio/stargazers :blush: :christmas_tree:
