### ISSUE TITLE
ESP8266 RTOS SDK

### ISSUE THREAD

**Issue by andriyadi** [platformio/platformio#402]
I'm about to adopt ESP8266 native SDK, and since my use cases require parallelism, it would be great to adopt RTOS SDK. I've found this project, [ESP-OPEN-RTOS](https://github.com/SuperHouse/esp-open-rtos), somehow better than the official Espressif's.

Would it be possible to support this kind of SDK into Platformio?

Thanks in advance. Have a great holiday guys!

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-espressif8266/issues/16
