### ISSUE TITLE
add : thingspeak library

### ISSUE THREAD

**Issue by itsjustvenky** [platformio/platformio#409]
@ivankravets I request you to add this library to platformio.

This library has been improved and now works with ESP8266 too.

https://github.com/mathworks/thingspeak-arduino

Ref : 
http://community.thingspeak.com/2015/10/official-thingspeak-library-for-arduino-and-particle/?platform=hootsuite

**Comment by ivankravets** [comment]
Next time please post issue here https://github.com/platformio/platformio-libmirror/issues

**Comment by ivankravets** [comment]
Done https://github.com/mathworks/thingspeak-arduino/pull/4

**Comment by itsjustvenky** [comment]
@ivankravets  thanks.
