### ISSUE TITLE
Bug : Reinitialization of platform doesn't remove old platform info.

### ISSUE THREAD

**Issue by itsjustvenky** [platformio/platformio#416]
```
platformio init --ide eclipse --board esp01_1m
```
and I see this info. inside platformio.ini
```
[env:esp01_1m]
platform = espressif
framework = arduino
board = esp01_1m
```

Now again I tried the same initialization command with different ESP type
```
platformio init --ide eclipse --board esp12e
```
and now I see both platform's listed inside platformio.ini
```
[env:esp01_1m]
platform = espressif
framework = arduino
board = esp01_1m

[env:esp12e]
platform = espressif
framework = arduino
board = esp12e
```

**Comment by ivankravets** [comment]
This is not a bug, this a feature. The idea of `platformio.ini` is to have more that one environment. See doc http://docs.platformio.org/en/latest/userguide/cmd_init.html

> Initialize new PlatformIO based project or update existing with new data.
