### ISSUE TITLE
esp8266  memory: No such file or directory

### ISSUE THREAD

**Issue by gpepe** [platformio/platformio#419]
Hi!
Following compile error:
.pioenvs/esp12e/ESP8266WiFi/WiFiClient.h:28:18: fatal error: memory: No such file or directory

platformio.ini:
[env:esp12e]
platform = espressif
framework = arduino
board = esp12e

platformio platforms list:
espressif   with packages: ldscripts, tool-esptool, framework-arduinoespressif, toolchain-xtensa

main.c:
https://github.com/esp8266/Arduino/blob/master/libraries/ArduinoOTA/examples/BasicOTA/BasicOTA.ino

What else should I install it?

best regards.

**Comment by ivankravets** [comment]
Please rename file to `*.cpp`. INO is CPP-based format, not C.
