### ISSUE TITLE
CMakeLists.txt add_executable has only one source file

### ISSUE THREAD

**Issue by hameno** [platformio/platformio#421]
Hello,
I'm not sure if this is a bug, missing feature oder just expected but when I run 
```platformio init --board uno --ide clion``` 
only one cpp file from my src folder is added to the ```add_executable``` setting.
I would expect all cpp files to be added there.

**Comment by ivankravets** [comment]
This is OK. CLion uses Cmake as core build system and depends on it. However, PlatformIO has own build system and doesn't depend on Cmake. PlatformIO generates minimal settings in `CMakeLists.txt` which are required to code autocompletion and etc.

**Comment by hameno** [comment]
But without them code completion in clion is not completely available for all files.

**Comment by ivankravets** [comment]
Sure? Could you provide me simple projects with more that 1 file where I will see problems with autocompletion and etc.

Thanks.

**Comment by hameno** [comment]
Sure, but it is not exactly code completion thats not working but rather the code insights on the side of the code (where the line numbers are). 
My test case consists of the main.cpp and one class with header and source. When not added to the CmakeLists.txt the header file will not show links to the implemented methods in the source.
This happens with latest stable of platformio (2.7.0) and clion (1.2.4).

With SampleClass.cpp added to add_executable:
![with_entry](https://cloud.githubusercontent.com/assets/365084/12071424/417e0d62-b0ac-11e5-9306-d76140f6dd68.PNG)
and without:
![without_entry](https://cloud.githubusercontent.com/assets/365084/12071423/417d895a-b0ac-11e5-911a-0489a86cded7.PNG)
[ClionSample.zip](https://github.com/platformio/platformio/files/75948/ClionSample.zip)

**Comment by ivankravets** [comment]
Thanks, will fix it.

**Comment by hameno** [comment]
Thanks :)

**Comment by ivankravets** [comment]
@hameno please re-test it with the latest http://docs.platformio.org/en/latest/installation.html#d-development-version

**Comment by hameno** [comment]
Looks good!

**Comment by diejmon** [comment]
What about files in ./lib folder? Code insights doesn't work in this folder.
_CLion 2016.3.2_
_PlatformIO, version 3.3.0a10_

**Comment by ivankravets** [comment]
@diejmon have you tried to re-init project as described in docs?
* http://docs.platformio.org/en/latest/ide/clion.html

**Comment by diejmon** [comment]
@ivankravets yes, just tried this again. If I add all files in ./lib folder to `add_executable(${PROJECT_NAME} ${SRC_LIST})` list, CLion works as expected.

**Comment by ivankravets** [comment]
@diejmon I've got you. Please file a new issue https://github.com/platformio/platformio-core

Thanks!

**Comment by diejmon** [comment]
@ivankravets Thanks for fast response! Will create a new issue soon.

**Comment by diejmon** [comment]
#897
