### ISSUE TITLE
Update framework-arduinoteensy

### ISSUE THREAD

**Issue by gefla** [platformio/platformio#434]
Hi,

the framework-arduinoteensy package is out of date. It is older than at least https://github.com/PaulStoffregen/cores/commit/f2948bd19530a2298edcba315e888d35325cc0d0, which is required for DMA UART operation.

As a side note, I have tried finding documentation on the package system and determine
* what source the package was built from
* how to send an update myself

Did I just miss the docs?

     Goodbyte, Gerd.

**Comment by ivankravets** [comment]
@gefla thanks! I'll update `framework-arduinoteensy`. If you like PlatformIO, please give us a :star: https://github.com/platformio/platformio/stargazers

**Comment by ivankravets** [comment]
@gefla please `platformio update`.

**Comment by ivankravets** [comment]
@PaulStoffregen could you make release/tag for https://github.com/PaulStoffregen/cores in future? I've just subscribed to your repository and will be notified for the new releases. Thanks a lot!

**Comment by gefla** [comment]
As mentioned on gitter: Done, works.

**Comment by PaulStoffregen** [comment]
I generally don't use github to release Teensyduino.  I'll try to tag releases, but odds are strong I'll tend to neglect that step.  My release process already involves a lot of non-github steps!

**Comment by ivankravets** [comment]
@PaulStoffregen Thanks! I'll try to monitor it manually too.
