### ISSUE TITLE
Chipkit PIC32 boards support

### ISSUE THREAD

**Issue by deladriere** [platformio/platformio#438]
I would love to have PIC32 boards supported, thanks
How come they are all absent from Platformio?

ChipKIT boards: http://chipkit.net

**Comment by deladriere** [comment]
Sorry but I can't find how to apply labels to this issue (board ...)
could someone do it ?
thx

**Comment by deladriere** [comment]
PIC32 are now supported by Arduino IDE. Maybe now it could also workk on PIO ?
see : https://raw.githubusercontent.com/chipKIT32/chipKIT-core/master/package_chipkit_index.json

**Comment by adilinden** [comment]
Yes, would be nice to see chipKIT32 support.  It would make my day :)

**Comment by ivankravets** [comment]
@deladriere , @adilinden  please re-test the latest http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by ivankravets** [comment]
Final firmware doesn't work. I reopen issue.
