### ISSUE TITLE
Not clear how to overwrite $BOARD.options.resetmethod ..

### ISSUE THREAD

**Issue by seclorum** [platformio/platformio#444]
I would like to force my board.options.resetmethod="ck", but see no way to do that outside of editing the board.json file .. is there a way to override this for my board in a project-local config?  (i.e. through platformio_extra_script.py - tried to override it like "esp12.board.options.resetmethod=ck" but no go ..

**Comment by valeros** [comment]
Hi @seclorum!
How about create [custom board](http://docs.platformio.org/en/latest/platforms/creating_board.html) based on `esp12` with needed reset method?

**Comment by seclorum** [comment]
I'd really rather not do that, since it means maintaining another set of file(z) outside the project repository - rather would like to know how to over-ride the defaults for this key:

````
    "esp12e": {
        "build": {
            "core": "esp8266",
            "extra_flags": "-DESP8266 -DARDUINO_ARCH_ESP8266 -DARDUINO_ESP8266_ESP12",
            "f_cpu": "80000000L",
            "ldscript": "esp8266.flash.4m.ld",
            "mcu": "esp8266",
            "variant": "nodemcu"
        },
        "frameworks": ["arduino"],
        "name": "Espressif ESP8266 ESP-12E",
        "platform": "espressif",
        "upload": {
            "maximum_ram_size": 81920,
            "maximum_size": 4194304,
            "resetmethod": "ck",
            "require_upload_port" : true,
            "speed": 115200
        },
        "url": "http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family",
        "vendor": "Espressif"
    },
````

**Comment by ivankravets** [comment]
@seclorum how about http://docs.platformio.org/en/latest/projectconf.html#extra-script ?

**Comment by ivankravets** [comment]
Please use http://docs.platformio.org/en/latest/projectconf.html#extra-script

`platformio.ini`
```ini
[env:esp12e]
platform = espressif
framework = arduino
board = esp12e
extra_script = extra_script.py
```

`extra_script.py`
```python
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()
env['BOARD_OPTIONS']['upload']['resetmethod'] = 'ck'
```

**Comment by ivankravets** [comment]
See http://docs.platformio.org/en/latest/platforms/espressif.html#custom-reset-method

**Comment by ivankravets** [comment]
Implement `upload_resetmethod` option for http://docs.platformio.org/en/latest/projectconf.html#uploading-options

Ping @crushedice2000

**Comment by ivankravets** [comment]
Please re-test with the latest http://docs.platformio.org/en/latest/installation.html#d-development-version

**Comment by ivankravets** [comment]
Docs: http://docs.platformio.org/en/latest/platforms/espressif.html#custom-reset-method

**Comment by crushedice2000** [comment]
@ivankravets: Thank you very much!

**Comment by seclorum** [comment]
Thanks!
