### ISSUE TITLE
Specficy upload port for Mac AND windows ?

### ISSUE THREAD

**Issue by donnib** [platformio/platformio#451]
Hi,
Is there a way to specify an upload port both for mac and windows ? I work both on windows and on mac on the same project. 

donnib

**Comment by ivankravets** [comment]
Please take a look at http://docs.platformio.org/en/latest/projectconf.html#extra-script

```python
from platform import system
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()

if system().lower() == "windows":
    env.Replace(UPLOAD_PORT="COM13")
else:
    env.Replace(UPLOAD_PORT="/dev/tty.serialport")
```

**Comment by ivankravets** [comment]
Sorry, why do you need to specify directly `upload_port`? PlatformIO can automatically find upload port. Try `platformio run -t upload` without specifying `upload_port` or `--upload-port`.

**Comment by ivankravets** [comment]
Please reopen issue if you need help.

P.S: We would be thankful for a star :star:  https://github.com/platformio/platformio/stargazers
