### ISSUE TITLE
SPL-Framework support for Nucleo F401RE board

### ISSUE THREAD

**Issue by g7uvw** [platformio/platformio#453]
A request to add SPL framework support for the Nucleo F401RE board. CMSIS works well, but there are some higher level features in SPL that would be very nice to have access to.

**Comment by ivankravets** [comment]
Please install development version http://docs.platformio.org/en/latest/installation.html#d-development-version

**Comment by g7uvw** [comment]
I'll try it out first thing tomorrow.

thanks.

**Comment by g7uvw** [comment]
Sorry - only just had time to get to test this.
It looks like the framework-spl is missing some files.
It's definitely missing stm32f4xx_hal.h and stm32f4xx_hal_rcc.h
My build gives up at that point.

**Comment by valeros** [comment]
Hi @g7uvw these files `stm32f4xx_hal.h` and `stm32f4xx_hal_rcc.h` belong to ST HAL library.

**Comment by g7uvw** [comment]
Ok, I think I'm misunderstanding something.
I thought the SPL was built upon the HAL. I'll have to go away and read some more.
