### ISSUE TITLE
Board compatibility with more than one platform

### ISSUE THREAD

**Issue by WisniewskiP** [platformio/platformio#456]
At this moment it is only possible to configure board with one compatible platform. It would be nice to have board that supports more platforms at the same time (different compilers for the same target)

**Comment by ivankravets** [comment]
Docs: http://docs.platformio.org/en/latest/platforms/creating_board.html

Usage
```
  "platforms": [
    "teensy", 
    "atmelavr",
    "..."
  ], 
```
