### ISSUE TITLE
Donating to PlatformIO development

### ISSUE THREAD

**Issue by jasonmhite** [platformio/platformio#478]
I really like PlatformIO and would like to support its development. I'm just a student so it wouldn't be anything huge, but I'd like to make a donation. Is there a way to set up to do this? I searched here and on the main page and couldn't find any mention apart from Bountysource, which isn't the same thing as donating.

**Comment by ivankravets** [comment]
Thanks a lot!!! I've just added button to the README page https://github.com/platformio/platformio

P.S: We use our local Ukrainian payment system because PayPal doesn't work in Ukraine.

**Comment by ivankravets** [comment]
See new page http://platformio.org/#!/donate

**Comment by jasonmhite** [comment]
Ah yes, that is much better. I tried to donate with the old system, but it wouldn't authorize my payment. The new Bountysource donations work much better.

Keep up the good work! I keep hearing more and more people praising PlatformIO, so you definitely have people's attention.

**Comment by ivankravets** [comment]
Thanks a lot for the donation and warm words!
