### ISSUE TITLE
[platformio-ide 0.3.2] Windows setup affected by virtualenv 14.0.2/14.0.3 bug

### ISSUE THREAD

**Issue by hemanth7787** [platformio/platformio#488]
The virtualenv.tar.gz included tin the windows package uses virtualenv 14.0.3 which is known to have problem with windows. Resulting in partial non-working installation.

Details of the virtualenv bug:
https://github.com/pypa/virtualenv/issues/856

**Comment by ivankravets** [comment]
Thanks! PlatformIO IDE 0.3.3 is released!

P.S: Next time please use this repo https://github.com/platformio/platformio-atom-ide
