### ISSUE TITLE
Arduino framework does not work with network boot. 

### ISSUE THREAD

**Issue by rwalli** [platformio/platformio#491]
Code (e.g blink.ino) generated with platformio-2.8.2 or platformio-3.0.0dev fails to work with Ariadne or Netload bootloader.
If i compile with various versions of the Arduino IDE the upload over ethernet works.
see also https://github.com/codebendercc/Ariadne-Bootloader/issues/22

Robert

**Comment by rwalli** [comment]
Update: found out that the issue results from binary validation in the bootloader but i can't figure out why
PlattfromIO produces different kind of binaries with the same compiler.
Could you please delete this topic until i find more details.

**Comment by ivankravets** [comment]
PlatformIO uses own code builder and build flow. We don't hide what we build. You can see all commands in the build output. Please contact with authors of the bootloader.
