### ISSUE TITLE
Depend on a library using GitHub URL

### ISSUE THREAD

**Issue by probonopd** [platformio/platformio#498]
Wouldn't it be nice if we could
`#include "https://raw.githubusercontent.com/Makuna/NeoPixelBus/814a4f0250d408b6f0b7252537352ce0b93e4b3d/src/NeoPixelBus.h"`?

Golang seems to work somewhat like this, iirc. 

The result would be painless dependency management:
 * Can reference any specific commit of any library on GitHub - even feature branches and development versions
 * Do not need to wait for libraries to be "included" or "submitted" to any central repository

Rough idea of how to implement:
At compile time, platformio would have to download the URLs and any files referenced therein, place them into `.pioenvs`, and replace the URL include statement with one that would reference the downloaded local file.

**Comment by loopj** [comment]
This would effectively require code parsing and rewriting, which seems a little funky in c/c++ land. Go already has this concept built in to the language.

Having github urls in the code would make for very unportable code, and would tightly bind code to platformio's build system.

Just my 2c.

**Comment by gerritv** [comment]
You assume that everything is connected to the internet all the time, not something you should count on. Also any notion of repeatable builds goes out the door. No serious development organization would use this. There is no Change Management (those parts of your code can change at the other parties whim while you are building),non repeatable builds, no sane possibility of source code control.

Plus not to mention that you expect platformio to parse your entire source code looking for #include lines (possibly inside #ifdef's!) before calling the compiler.

**Comment by probonopd** [comment]
> Also any notion of repeatable builds goes out the door.

Not if you include a specific SHA-1 hash

**Comment by ivankravets** [comment]
The parse source code and replace with real includes will bring a lot of problems to the different parts of PlatformIO. The integration with IDEs will not works. Code completion and code linting services will raise a lot of errors.

In any case, I'll allow defining of "dependency" as "git" URL.
