### ISSUE TITLE
[Espressif] setting board_f_cpu to 160mhz isn't working anymore

### ISSUE THREAD

**Issue by FWeinb** [platformio/platformio#501]
Since update to latest version the `board_f_cpu` flag seams to be used for defining the flash frequency and 160 isn't supported:

```
"/Users/FWeinb/.platformio/packages/tool-esptool/esptool" -eo "/Users/FWeinb/.platformio/packages/framework-arduinoespressif/bootloaders/eboot/eboot.elf" -bo .pioenvs/nodemcu/firmware.bin -bm dio -bf 160 -bz 4M -bs .text -bp 4096 -ec -eo .pioenvs/nodemcu/firmware.elf -bs .irom0.text -bs .text -bs .data -bs .rodata -bc -ec
error: invalid flash frequency value: 160
```

It looks like that [this](https://github.com/platformio/platformio/commit/d658363b5307da5ce3b2f99abe605103a360a605) is the commit that breaks this.

**Comment by ivankravets** [comment]
Please re-test with http://docs.platformio.org/en/latest/installation.html#d-development-version

**Comment by FWeinb** [comment]
This is working great! Thanks.

**Comment by ivankravets** [comment]
@FWeinb Thanks for the report! :+1:

**Comment by sticilface** [comment]
Works for me!  thanks
