### ISSUE TITLE
Modifying any lib file under the .pioenvs affects the original

### ISSUE THREAD

**Issue by syedatifakhtar** [platformio/platformio#509]
To replicate-:

1.Modify any .h or .cpp file of any libs you are using under the .pioenvs folder
2.Delete the .pioenvs folder
3.Trigger a build again

Expected - Platformio should fetch the lib files from the repositories again
Actual - Old modified libs are pulled back into the .pioenvs and build keeps failing in case something was wrongly modified.

Also noticed,if you keep any file open and the editor crashes,the files are sometimes truncated and the contents lost,this compounds the effects of the above issue.

**Comment by ivankravets** [comment]
`.pioenvs` is temporary directory. Don't edit code within it.
