### ISSUE TITLE
Docs are a mess

### ISSUE THREAD

**Issue by jsprenkle** [platformio/platformio#517]
Tried to install as a newbie. Multiple copies of Installation instructions so which to use is not clear. Docs section tells me to use 'pip' program to install platformio. What's a pip and how do I get it (not everyone is a python programmer)? Tells me to find the 'type' for my board but dev environment browser doesn't spell out what the 'type' of a board is. You guys seriously need to reduce the friction to use your IDE or nobody will succeed.

**Comment by ivankravets** [comment]
> Multiple copies of Installation instructions so which to use is not clear. 

What do you mean under multiple copies?

>  Docs section tells me to use 'pip' program to install platformio. What's a pip and how do I get it (not everyone is a python programmer)?

I've just updated docs and website. The website will be deployed later. Thanks.

> Tells me to find the 'type' for my board but dev environment browser doesn't spell out what the 'type' of a board is. 

* http://docs.platformio.org/en/latest/userguide/cmd_boards.html
* http://platformio.org/#!/boards

> You guys seriously need to reduce the friction to use your IDE or nobody will succeed.

Thanks a lot for the feedback. We will improve our docs.

**Comment by ivankravets** [comment]
Please reopen if you still need help
