### ISSUE TITLE
Set the upload_port setting via an environment setting rather than platformio.ini

### ISSUE THREAD

**Issue by tonykambo** [platformio/platformio#518]
@ivankravets 

It would be appreciated if we could set the upload_port setting currently found in platformio.ini (in support of OTA firmware updates) to be set via environment variable rather than hard coding IP address in platform.ini. This will help with team development using repo and avoid having to manually change IP.

Thanks.

**Comment by ivankravets** [comment]
Implemented in https://github.com/platformio/platformio/commit/dc007dd136836b8beed185fb35fb03a33e1052d3
