### ISSUE TITLE
IDE keep showing "Reload Now" popup at launch

### ISSUE THREAD

**Issue by rajendra2** [platformio/platformio#524]
Hello,

I just started to use platformIO on mac OS X. I keep getting popup whenever I launch the IDE. It says Installing IDE... and after completion, there is option to Reload Now.

After choosing "Reload Now", it agains tries installing IDE and show option to Reload Now. This keeps happening and I can only get out of it if I choose , Reload later. I am guess this is not a normal behavior.  Any workaround ?

<img width="1150" alt="screen shot 2016-02-20 at 5 25 26 pm" src="https://cloud.githubusercontent.com/assets/15102803/13196562/539a890e-d7f7-11e5-93f7-df1e01945948.png">
<img width="1203" alt="screen shot 2016-02-20 at 5 25 01 pm" src="https://cloud.githubusercontent.com/assets/15102803/13196561/53974956-d7f7-11e5-942b-11f31c9e2780.png">

**Comment by ivankravets** [comment]
I see it. Sorry. Give me a few minutes.

**Comment by ivankravets** [comment]
Please sorry for that issue:

* Please click on "Reload Later"
* Then click on `gear` icon on PlatformIO IDE Toolbar which will open Atom's Settings
* Then go to `Settings > Packages` and upgrade PlatformIO IDE to 1.0.4.
* Restart IDE

**Comment by rajendra2** [comment]
That was fast!

I have followed the steps and the popup is no longer coming after reloading. 

Thanks
