### ISSUE TITLE
avrdude: ser_open(): can't open device "\\.\COM4": Access is denied.

### ISSUE THREAD

**Issue by Vikaton** [platformio/platformio#525]
I'm trying to build my arduino project and upload it, but when the build commands commence, I get an error

`avrdude: ser_open(): can't open device "\\.\COM4": Access is denied.`

I tried running Atom itself as admin but that didn't seem to do the trick, any pointers?

**Comment by ivankravets** [comment]
Did you close all Terminal windows with Serial Port Monitor?

**Comment by Vikaton** [comment]
@ivankravets That seemed to do the trick, thanks! I had the arduino IDE Monitor open

**Comment by ela21ccc** [comment]
what do you mean by closing the serial monitor?

**Comment by ivankravets** [comment]
@ela21ccc just reconnect your board

**Comment by Mohit2183** [comment]
i am getting this error "avrdude: ser_open(): can't open device "\\.\COM4": Access is denied." what to do , i have tried with reconnecting it too

**Comment by ivankravets** [comment]
It seems that this port is used by another other application. Try to disconnect it from other apps.

**Comment by Mohit2183** [comment]
thanks ivankravets

**Comment by jmcdaris** [comment]
I'm getting this same error.  I think I've done all the things mentioned above and still no luck.  What else can I try?

**Comment by Rultem** [comment]
jmcdaris, Did you solve it?

**Comment by tophat17** [comment]
I have no idea why but my issue when away after I closed Cura slicer. Make sure you don't have any programs on your computer open that eat all your ports.

**Comment by chubylive** [comment]
Yeah Cura hugs your serial port like no other. you can disable the USB printer plugin

**Comment by stadekawa** [comment]
Took too long to find this solution; closing Cura solved my issue. Thank you!

**Comment by PhilRabbittBJ** [comment]
Yep Cura was the culprit for me too :-)
Thanks.

**Comment by Lookingformybrother** [comment]
I tried to disconnect everything, close IDE and connect and open IDE again, but didn't work. for me it was Tools->Port -> and pick the port that is available there :)

**Comment by locrider246** [comment]
> Reference

Thank you. I had the same error and I solved it thanks to your instruction.
