### ISSUE TITLE
support for Espressif ESP8266 ESP-07

### ISSUE THREAD

**Issue by thewilli** [platformio/platformio#527]
according to the list of [supported boards](http://docs.platformio.org/en/latest/platforms/espressif.html#espressif) you seem only to support the ESP-01 and ESP-12E of the [ESP8266 generic board family](http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family). 

The [ESP-07](http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family#esp-07) is quite handy because it not only has more GPIOs than the ESP-01, but also has an integrated antenna as well as a jack for connecting an external one.

Could you please add support for the ESP-07 as well?

**Comment by ivankravets** [comment]
You can use ESP-12 based board. For example, could you try `esp12e` or `nodemcu`? Do they work?
