### ISSUE TITLE
Refactor platform build scripts

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#528]
Need to refactor all build scripts and put base flags to appropriate SCOPES. More details http://docs.platformio.org/en/latest/projectconf.html#build-flags

User should have ability to pass own build flags and override base settings. In this case, user's flags should follow after "base flags".

**Comment by ivankravets** [comment]
Related issue https://github.com/platformio/platformio-atom-ide/issues/54 where `build_flags = -Wno-comment` doesn't work.

**Comment by sstaub** [comment]
I tried to use build_flags = -Wno-comment in platformio.ini, but it doesn't work.

**Comment by ivankravets** [comment]
@sstaub do you use the latest development version? `platformio --version`

**Comment by sstaub** [comment]
The IDE is v1.04

**Comment by sstaub** [comment]
Sorry, version of platformio is 2.7.1

> Am 01.03.2016 um 10:25 schrieb Ivan Kravets <notifications@github.com>:
> 
> platformio --version

**Comment by ivankravets** [comment]
@sstaub Gear Icon(Settings) on the PlatformIO Toolbar > Packages > platformio-ide > Settings > Use development version of PlatformIO

P.S: Don't forget to uncheck it when 2.8.5 will be released.

**Comment by sstaub** [comment]
It did the check in the settings long times ago. But i don’t know which version is now currently installed:

**Comment by ivankravets** [comment]
Then Menu > PlatformIO > Upgrade PlatformIO.

It will install the latest development version.

**Comment by sstaub** [comment]
The problem is that I do upgrading (see screenshot), but when I ask which version installed 
with platformio —version it says 2.7.1

**Comment by ivankravets** [comment]
Open system Terminal (not in IDE), run `pip uninstall platformio`. Restart IDE

**Comment by sstaub** [comment]
No changes.

**Comment by ivankravets** [comment]
Which is your OS?

**Comment by sstaub** [comment]
MacBookPro Yosemite 10.10.5

**Comment by ivankravets** [comment]
Give me please an output:
1. Open terminal in IDE: `which platformio`
2. Open System OS terminal: `which platformio`

**Comment by sstaub** [comment]
> Am 01.03.2016 um 11:31 schrieb Ivan Kravets <notifications@github.com>:
> 
> Give me please an output:
> 1. Open terminal in IDE: which platformio
> 
stefans-mbp-3:OSCwing sstaub$ stefans-mbp-3:~ sstaub$ which platformio
bash: stefans-mbp-3:~: command not found
stefans-mbp-3:OSCwing sstaub$ /usr/local/bin/platformio
Usage: platformio [OPTIONS] COMMAND [ARGS]...

> 2. Open System OS terminal: which platformio
> 
> 
stefans-mbp-3:~ sstaub$ which platformio
/usr/local/bin/platformio
stefans-mbp-3:~ sstaub$

**Comment by ivankravets** [comment]
Hm... And `pip list` in the both Terminals (IDE + OS)

**Comment by sstaub** [comment]
says platformio (2.7.1) in both terminals

**Comment by ivankravets** [comment]
Please mail me@ikravets.com directly.
