### ISSUE TITLE
platformio forum

### ISSUE THREAD

**Issue by malachib** [platformio/platformio#530]
Requesting a forum where us end-users can interact without having to always bother YOU Ivan =)

I propose it be broken down by platform & framework

**Comment by ivankravets** [comment]
How about to use our https://www.reddit.com/r/platformio/ ? It isn't popular but we can promote it on the our site.

**Comment by malachib** [comment]
In this context reddit appears fairly unstructured.  I'd love to be able to go to say an 32u4 or STM32 or mbed dedicated area and see what's being discussed -- and have that distinct from your official announcements, etc.  I am not so sure reddit works well for that

**Comment by ivankravets** [comment]
How about https://www.discourse.org ?

**Comment by ivankravets** [comment]
Also, who will support it?

**Comment by malachib** [comment]
discourse.org looks promising.  I can't offer real / full support, but I can lend a hand moderating here and there

**Comment by ivankravets** [comment]
Welcome to PlatformIO Community :) http://community.platformio.org

**Comment by malachib** [comment]
nice!!
