### ISSUE TITLE
error: 'Serial' undeclared (first use in this function)

### ISSUE THREAD

**Issue by rajendra2** [platformio/platformio#532]
my code:
/* next line includes Arduino.h */
#include <Arduino.h>

void setup() {
  Serial.begin(9600);
}

void loop () {
  Serial.print("hello world");
}

Executing: platformio run 
[Mon Feb 22 10:27:34 2016] Processing due (platform: atmelsam, board: due, framework: arduino, build_flags: -lstdc++)
--------------------------------------------------------------------------------
arm-none-eabi-gcc -o .pioenvs/due/src/main.o -c -g -Os -ffunction-sections -fdata-sections -Wall -mthumb -mcpu=cortex-m3 -nostdlib -DF_CPU=84000000L -DUSBCON -DUSB_MANUFACTURER="PlatformIO" -Dprintf=iprintf -D__SAM3X8E__ -DARDUINO_SAM_DUE -DARDUINO_ARCH_SAM -DUSB_VID=0x2341 -DUSB_PID=0x003e "-DUSB_PRODUCT=\"Arduino Due\"" -DARDUINO=10606 -DPLATFORMIO=020804 -I.pioenvs/due/FrameworkArduino -I.pioenvs/due/FrameworkCMSISInc -I.pioenvs/due/FrameworkLibSam -I.pioenvs/due/FrameworkLibSam/include -I.pioenvs/due/FrameworkDeviceInc -I.pioenvs/due/FrameworkDeviceInc/3x8e/include -I.pioenvs/due/FrameworkArduinoVariant src/main.c
src/main.c: In function 'setup':
src/main.c:4:3: error: 'Serial' undeclared (first use in this function)
Serial.begin(9600);
^

**Comment by ivankravets** [comment]
You can't use C++ code in C file. Please rename file to `main.cpp`.
