### ISSUE TITLE
Websockets for Arduino ESP8266 throws errors 

### ISSUE THREAD

**Issue by kristsm** [platformio/platformio#534]
I installed websockets library but even then compiler throws following errors:

scons: *** [.pioenvs\esp12e\WebSockets_ID549\WebSockets.o] Error 1
.pioenvs\esp12e\WebSockets_ID549\WebSocketsClient.cpp: In member function 'void WebSocketsClient::begin(const char*, uint16_t, const char*, const char*)':
.pioenvs\esp12e\WebSockets_ID549\WebSocketsClient.cpp:67:16: error: 'RANDOM_REG32' was not declared in this scope
randomSeed(RANDOM_REG32);
^
scons: *** [.pioenvs\esp12e\WebSockets_ID549\WebSocketsClient.o] Error 1
 [ ERROR ] Took 13.12 seconds 

It seems ESP8266 core files are not up to date. Can I solve this myself like - updating Platformio ESP8266 arduino framework with latest official ESP8266 Arduino github repository?

Thanks!

**Comment by valeros** [comment]
Hi @kristsm `RANDOM_REG32` is defined in RC framework version, please follow [these instructions](https://github.com/platformio/platformio/issues/401#issuecomment-166958952) to use the latest framework.

**Comment by kristsm** [comment]
Hi, valeros! Thanks for the help! Your instructions healed compiling problem. 

Still Websockets are not working, but it might also be related to my code.

**Comment by ivankravets** [comment]
@kristsm please provide project to reproduce this issue

**Comment by kristsm** [comment]
Hi! No worries, I checked the websocket part of the code and everything is working fine !

**Comment by ivankravets** [comment]
@kristsm please https://twitter.com/platformio_org/status/704304862998224896 and report us.

**Comment by ivankravets** [comment]
Please reopen this issue if you still have problems
