### ISSUE TITLE
Update ESP8266/Arduino to 2.1

### ISSUE THREAD

**Issue by loopj** [platformio/platformio#544]
New version just released with a ton of bug fixes: https://github.com/esp8266/Arduino/releases/tag/2.1.0

**Comment by ivankravets** [comment]
Please re-test with https://twitter.com/platformio_org/status/704304862998224896

**Comment by loopj** [comment]
Thanks @ivankravetz!

**Comment by ivankravets** [comment]
@loopj you should say thank to @valeros :blush:
