### ISSUE TITLE
Support for LPCXpresso boards

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio#547]
Can you support boards for LPCXpresso, like CD Boards for LPC1769 and LPC1115 ...?
They have their own framework and way to upload but they can be used with mbed with some modifications. There are also some other mbed enabled boards.
I want to port mbed projects from LPC1768 (Seeeduino Arch Pro) to the cheaper LPC1769 CD Board.

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-nxplpc/issues/1
