### ISSUE TITLE
Programs don't run after todays update

### ISSUE THREAD

**Issue by jaroslavas** [platformio/platformio#551]
Today, program asked me to update itself and some of the libraries. After the update platformio works weird - after I press upload, (I'm using ESP8266) it writes that it uploads but no dots are shown as usual, only after some time they appear in the console and console is closed immediately. After that, sketch doesn't run. If I compile program in Arduino IDE, everything works ok.

Atom version 1.5.3-3e71894
IDE 1.0.4 | CLI 2.8.4
Board: ESP8266-201

**Comment by ivankravets** [comment]
Which was your previous version?

**Comment by jaroslavas** [comment]
I'm not sure which version it was, but I downloaded it on February 23rd

**Comment by ivankravets** [comment]
Please provide your `platformio.ini` file

**Comment by valeros** [comment]
Hi @jaroslavas
Could you please also try to erase flash via `path/esptool -cp <port_name> -cd ck -ce` and than upload program again.

**Comment by jaroslavas** [comment]
my platformio.ini:

```
[env:esp12e]
platform = espressif
framework = arduino
board = esp12e
```

**Comment by ivankravets** [comment]
@jaroslavas please try https://github.com/platformio/platformio/issues/551#issuecomment-191690336

**Comment by jaroslavas** [comment]
Are we speaking aboy [esptool.py](https://github.com/themadinventor/esptool) or [esptool-ck](https://github.com/igrr/esptool-ck)? Or maybe some other? :)

**Comment by jaroslavas** [comment]
OK, it's the second one. And... it helped! Thank you!
Maybe you know what happened?

And one more question - now, immediately after the build and flashing ended, that part of the window flashes green and closes immediately, is it possible to make it stay?

**Comment by valeros** [comment]
@jaroslavas Try `PlatformIO > Settings > Build Panel > Keep visible`

You mentioned above you are using `ESP8266-201` board which has 512Kb flash memory, but in your `platformio.ini` you chose `esp-12` board with 4Mb  flash. Is it OK for you?

**Comment by ivankravets** [comment]
@jaroslavas please reopen this issue if you still have any problems
