### ISSUE TITLE
MySensors Gateway example not compiling

### ISSUE THREAD

**Issue by gerritv** [platformio/platformio#558]
Attached is a project directory which fails to build using `platformio` but builds ok using VisualMicro and Arduino IDE 1.6.7. Using MySensors development branch, not the 1.5.4 library.
Also attached are two build outputs ( from Visual Micro and other from platformio) and the envdump.
Platformio version is 2.8.5.dev2 running on Windows 10 with python 2.7. The problem arises when building for Arduino nano as well, doesn't seem ESP8266 specific. My guess is that there is a flaw in the convoluted Arduino file finding algorithm. Platformio seems to want to build files that are not relevant to the .ino in question.

[SensorNet.zip](https://github.com/platformio/platformio/files/158823/SensorNet.zip)
[envdump.txt](https://github.com/platformio/platformio/files/158824/envdump.txt)

[PlatformioOutput.txt](https://github.com/platformio/platformio/files/158825/PlatformioOutput.txt)
[VisualMicroOutput.txt](https://github.com/platformio/platformio/files/158827/VisualMicroOutput.txt)

**Comment by valeros** [comment]
Hi @gerritv 
Indeed, MySensors library has an unusual build logic. Please have a look at #331 
I've created a working [project](https://dl.dropboxusercontent.com/u/10025728/mysensors.zip) for you, could you test it?

**Comment by gerritv** [comment]
Awesome, it works. I guess next time I see these symptoms I will have to try this method. Sadly Arduino projects seem to provoke some really obtuse habits in structure :-(
