### ISSUE TITLE
Solution if terminal-plus is already installed

### ISSUE THREAD

**Issue by brbrr** [platformio/platformio#560]
I have already installed terminal-plus package. Is there any way to select which terminal to use?

**Comment by ivankravets** [comment]
The original `terminal-plus` is not compatible with PlatformIO IDE. I propose you to use `platformio-ide-terminal` which we maintain now.

**Comment by ivankravets** [comment]
I want to note, that `platformio-ide-terminal` has the same functionality that original package + additional enhancements. You can use single terminal for both cases.

**Comment by brbrr** [comment]
May I know what the difference with `terminal-plus' ?

**Comment by ivankravets** [comment]
@brbrr please take a look at https://github.com/platformio/platformio-atom-ide-terminal/blob/master/CHANGELOG.md

**Comment by brbrr** [comment]
Ah, of course :sweat_smile:
Thanks!

**Comment by ivankravets** [comment]
In a nutshell, API to pass own commands to it + refactored "status panel" which was moved to native Atom's status bar (saved 30px and empty line ) :)

**Comment by ivankravets** [comment]
What is more, we are glad to move our improvements to original terminal. See https://github.com/jeremyramin/terminal-plus/pull/160

However, @jeremyramin doesn't support this project and no one has access to it :(

**Comment by brbrr** [comment]
Ah, I see. there definitely lack of activity in original project.
