### ISSUE TITLE
How to add support for new board?

### ISSUE THREAD

**Issue by adilinden** [platformio/platformio#562]
Hi,

I am hoping to create proper Arduino cores for ATmega32U4 and ATmega1284P boards I did some time ago.  However, I much prefer PlatformIO over the Arduino IDE.  How do I go about adding these to PlatformIO?

Thanks,
Adi

**Comment by ivankravets** [comment]
How about http://docs.platformio.org/en/latest/platforms/index.html#custom-platform-board ?

For your information, this complicated process will be simplified in PlatformIO 3.0. See https://github.com/platformio/platformio/issues/479

**Comment by ivankravets** [comment]
Please reopen this issue if you have any questions.
