### ISSUE TITLE
Default env target for multi-environment situations

### ISSUE THREAD

**Issue by malachib** [platformio/platformio#576]
As per [http://community.platformio.org/t/multitarget-refinement-when-developing-for-many-boards-at-once/32/8](url) I would like a way to specify a "default" build/run environment, in addition and contrast to the already-existing -e option

**Comment by ivankravets** [comment]
Please re-test with the latest http://docs.platformio.org/en/latest/installation.html#development-version

Docs: http://docs.platformio.org/en/latest/projectconf.html#env-default

**Comment by malachib** [comment]
roger that
