### ISSUE TITLE
donate link broken

### ISSUE THREAD

**Issue by ogail** [platformio/platformio#579]
I didn't know where to post this but going to http://platformio.org/donate then click http://platformio.org/donate/50 or any of the buttons More/100/50/25 etc.. will result in 404

<img width="1316" alt="screen shot 2016-03-14 at 2 08 09 pm" src="https://cloud.githubusercontent.com/assets/1034045/13754662/301ce1c6-e9ee-11e5-94ec-a3c2ab257c7d.png">

**Comment by ivankravets** [comment]
Thanks a lot for the repo. Fixed in https://github.com/platformio/platformio-web/commit/397bef4105ed51866e7143e4dd5a1b839e3a7b47

Please check http://platformio.org/donate
