### ISSUE TITLE
Faster flashing for ESP8266 (and CC3200) boards

### ISSUE THREAD

**Issue by georgkreimer** [platformio/platformio#592]
Flashing of the ESP8266 boards takes a while. Anybody who has flashed some of them noticed it's about a minute. I saw [this post](https://blog.cesanta.com/esp8266-superfast-flashing-flash-esp-in-5-seconds) blog today. Those guys at Cesanta Software have created a [modified version of the esptool](https://github.com/cesanta/fnc/blob/master/common/platforms/esp8266/stubs/esptool.py) but also have another flash tool called [Flash'N'Chips](https://github.com/cesanta/fnc) which reduces the flash times significantly. It would be great to have the flash time reduced for PlatformIO using these 2 options.

**Comment by ivankravets** [comment]
> Anybody who has flashed some of them noticed it's about a minute.
What is your board? Do you use specific LD script?

**Comment by georgkreimer** [comment]
Just verified with huzzah and NodeMCU breakout boards. It's around 40 sec for me. I'm using the default settings with the PlatformIO IDE

**Comment by Jorgen-VikingGod** [comment]
maybe this article could help to improve the flashing speed
https://blog.cesanta.com/esp8266-superfast-flashing-flash-esp-in-5-seconds

**Comment by eni23** [comment]
+1 for the idea that @Jorgen-VikingGod suggested. Using the modified esptool.py from the Mongoose platform (Source: https://github.com/cesanta/mongoose-flashing-tool/blob/master/common/platforms/esp8266/stubs/esptool.py) speeds up flashing a lot compared to the one shipped with PlatformIO:

PlatformIO esptool: `0m16.152s`
Modded esptool.py: `0m4.345s`


Until this or another fast flasher is integrated, one could do a workaround like this (only tested with PlatformIO 3):

Place the modded esptool to `tools/esptool-cesanta.py`

`platformio.ini`
```ini
[env:nodemcuv2]
platform = espressif
framework = arduino
board = nodemcuv2
upload_speed = 3000000
extra_script = tools/custom_uploader.py
```

`tools/custom_uploader.py`
```python
import os
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()
esptool_mod = "{0}/tools/esptool-cesanta.py".format(env['PROJECT_DIR'])
env.Replace(UPLOADER=esptool_mod)
env.Replace(UPLOADERFLAGS=[
    '--port',
    '$UPLOAD_PORT',
    'write_flash',
    '--flash_baud=$UPLOAD_SPEED',
    '0'
])
env.Replace(UPLOADCMD='$UPLOADER $UPLOADERFLAGS $SOURCE')
```

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-espressif8266/issues/15
