### ISSUE TITLE
esp-open-sdk and/or esp-open-rtos

### ISSUE THREAD

**Issue by MrDadaGuy** [platformio/platformio#593]
Feature Request:

Please implement [esp-open-sdk](https://github.com/pfalcon/esp-open-sdk) and/or [esp-open-rtos](https://github.com/SuperHouse/esp-open-rtos) support.

Thanks for a great product!!

**Comment by ivankravets** [comment]
Duplicate of #366 and #402.

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-espressif8266/issues/14
