### ISSUE TITLE
ATSAMD (zeroUSB) compilation appears broken

### ISSUE THREAD

**Issue by malachib** [platformio/platformio#598]
I've tried compiling many different test programs including a simple blinky, but all give a whole slew of errors not finding tons of symbols, starting with:

"In file included from .pioenvs/spark_samd/FrameworkArduino/Arduino.h:61:0,
from src/main.cpp:1:
.pioenvs/spark_samd/FrameworkArduino/WVariant.h:93:36: error: 'TCC_INST_NUM' was not declared in this scope"

and including other symbols such as Sercom, UsbHostDescriptor, and a lot more

Testing done on Debian Jessie and Mac OS X

**Comment by valeros** [comment]
Thanks! Fixed in the new framework package.  Please update via `pio update`.

**Comment by ivankravets** [comment]
Please test development version http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by malachib** [comment]
Compiling once again! Thank you guys
