### ISSUE TITLE
Project generator for CodeBlocks IDE

### ISSUE THREAD

**Issue by ivankravets** [platformio/platformio#600]
Request: http://forums.codeblocks.org/index.php/topic,21049.msg143743/topicseen.html

**Comment by ivankravets** [comment]
Initial support by @valeros  https://github.com/platformio/platformio/commit/b67acfec9cdf61088f233dc20a40fac6a02f8f93

**Comment by valeros** [comment]
Implemented in https://github.com/platformio/platformio/commit/2c45f18fa138fdb22c086f4e3e4524a43fc60b05
