### ISSUE TITLE
mnbed library version

### ISSUE THREAD

**Issue by sstaub** [platformio/platformio#602]
Can you update the mbed library to build 117 ? Please

**Comment by ivankravets** [comment]
Sorry, could you explain what we should update? 

117 - is not mbed library. See http://platformio.org/lib/show/117/PCA9685

**Comment by sstaub** [comment]
That is the last version on github https://github.com/mbedmicro/mbed
the actual build in platformio is 114

**Comment by ivankravets** [comment]
Thanks! @valeros will update tomorrow.

**Comment by valeros** [comment]
Thanks. Updated to rev117.
