### ISSUE TITLE
No JSON output feature for Library Manager's "Search" command

### ISSUE THREAD

**Issue by gholdys** [platformio/platformio#604]
### Configuration

**Operating system**: Any

**PlatformIO Version** (`platformio --version`): 2.8.6

### Description of problem
The --json-output option in the PlatformIO CLI that works for such commands like "lib list" does not work for "lib search". 

#### Steps to Reproduce
`platformio lib search --json-output`

### Actual Results
`Error: no such option: --json-output`

### Expected Results
A list of libraries, that match the search criteria, in JSON format.

**Comment by ivankravets** [comment]
Please test it with the latest http://docs.platformio.org/en/latest/installation.html#development-version
