### ISSUE TITLE
NEW Library request: WifiManager

### ISSUE THREAD

**Issue by seclorum** [platformio/platformio#612]
Not sure if this is the right place to ask this, but can we get WifiManager added to the list of pio libraries available, somehow:

https://github.com/tzapu/WiFiManager

If there is a better way to get these libs included in the pio base release, please let me know ..

**Comment by seclorum** [comment]
Argh, sorry for my brainfart, its already in there.  Closing this.

**Comment by valeros** [comment]
Next time please add request here https://github.com/platformio/platformio-libmirror
