### ISSUE TITLE
Typo in the documentation

### ISSUE THREAD

**Issue by Lauszus** [platformio/platformio#618]
There is a typo in the following section of the readme: https://github.com/platformio/platformio/blob/develop/docs/ci/travis.rst#custom-build-flags.

It should read:
```yaml
    - export PLATFORMIO_BUILD_FLAGS="-D GLOBAL_MACROS_FOR_ALL_TEST_ENV"
```

**Comment by ivankravets** [comment]
Thank you for pointing out this issue. We have updated our docs.
