### ISSUE TITLE
Support for MKR1000

### ISSUE THREAD

**Issue by gepd** [platformio/platformio#620]
Will be SAMD Arduino/Genuino boards like MKR1000, supported soon or is possible to install it manually?

### Configuration

**Operating system**:

* OSX/Windows/Linux

### Additional info

Full information from arduino website: http://www.arduino.cc/en/Main/ArduinoMKR1000

**Comment by sathibault** [comment]
I'm willing to contribute if there is some documentation on what needs to be done to add a board.

**Comment by oxullo** [comment]
If I'm not mistaken, it can't be done without updating the arduinosam framework, adding the mkr1000 variant.
For what it matters, I added the board definition here: oxullo@6aac75d08d568123929770ceb285199cf3d30d32

**Comment by valeros** [comment]
Please install PlatformIO [dev version](http://docs.platformio.org/en/latest/installation.html#development-version) and update `framework-arduinosam` package via `platformio update`

**Comment by ivankravets** [comment]
@sathibault , @oxullo could you try the latest http://docs.platformio.org/en/latest/installation.html#development-version ? Need to understand that this issue is really fixed.

Thanks.

**Comment by oxullo** [comment]
@valeros @ivankravets works for me! (green light for build and upload for the blink example plus the sketch I'm currently working on)

**Comment by ivankravets** [comment]
@oxullo thanks a lot for the report!
