### ISSUE TITLE
Installed libraries throw "No such file or directory"

### ISSUE THREAD

**Issue by Coder-256** [platformio/platformio#621]
What kind of issue is this?

- [X] Bug report. If you’ve found a bug, please provide information below.

------------------------------------------------------------------

### Configuration

**Operating system**: Mac OS X El Capitan 10.11.4

**PlatformIO Version** (`platformio --version`): PlatformIO, version 2.8.6

### Description of problem

I installed a library, but it still gave an error: `No such file or directory`.

#### Steps to Reproduce

1. Create a new project.
2. Import an existing but not installed library.
3. Build. An error is correctly thrown.
4. Install the library.
5. Rebuild. The build is successful, but the error still appears.

### Actual Results

![Not found?](https://cloud.githubusercontent.com/assets/10134823/14580890/e3db2048-03ab-11e6-802b-6659e4e8cba7.png)

### Expected Results

![Successful build](https://cloud.githubusercontent.com/assets/10134823/14580896/f3c9b69a-03ab-11e6-9987-3b7666fa15d5.png)

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:uno]
platform = atmelavr
framework = arduino
board = uno

[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328
```

**Source file to reproduce issue:**
```cpp
#include "Arduino.h"
#include <SPI.h>
#include "Adafruit_BLE.h"

void setup() {
  
}

void loop() {
  
}
```

### Additional info

Closing and reopening the file fixes the issue.

**Comment by orgkhnargh** [comment]
Docs [say](http://docs.platformio.org/en/latest/ide/atom.html#intelligent-code-autocompletion):

> The libraries which are added/installed after initializing process will not be reflected in code linter. You need `Menu: PlatformIO > Rebuild C/C++ Project Index (Autocomplete, Linter)`.

This is happening when you are installing libraries while project is not open in the IDE. Then project configuration does not contain those libraries and linter shows the "No such file or directory" error. A project configuration will be updated automatically when you are installing a library and a project is opened (unless you explicitly disable this feature in the IDE settings). If you still see the message for some reason, just click `PlatformIO > Rebuild C/C++ Project Index (Autocomplete, Linter)` and the message will go away.

P. S.
Please report IDE-related issues to the [IDE repository](https://github.com/platformio/platformio-atom-ide/issues) directly.
