### ISSUE TITLE
#CLI 2.9.1 Upgrade on Mac in Atom

### ISSUE THREAD

**Issue by sembsa** [platformio/platformio#643]
Hello,  i have problem with CLI, when i open Atom and PlatformIO i see on Home Screen CLI 2.9.0 and button Upgrade NOW!. And if upgrade i see in terminal:
`You're up-to-date!
PlatformIO 2.9.1 is currently the newest version available.`

My hardware:
OS X 10.11.5 Beta
Atom 1.7.3

Where is problem ?

I sorry for my English.

![zrzut ekranu 2016-05-02 o 14 38 25](https://cloud.githubusercontent.com/assets/3901645/14954556/9b093092-1073-11e6-8bb2-09f4b8176ed6.png)

**Comment by ivankravets** [comment]
Looks like you have a few PlatformIO CLI installed on your machine. Please open system Terminal and run `pip uninstall platformio`.

**Comment by sembsa** [comment]
Thanks it's work now :) i'm uninstall on brew platformio.
Now is close inssue.
