### ISSUE TITLE
Getting Service Temporarily Unavailable sometimes..

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platformio#649]
Sometimes Travis build fails with Error:
[API] 503 Server Error: Service Temporarily Unavailable for url: http://api.platformio.org/lib/download/65

Example of failed build: https://travis-ci.org/blynkkk/blynk-library/jobs/128298093

**Comment by ivankravets** [comment]
Thanks a lot for the report. I've just changed "limit" policy for CI requests. Please report me if you will see these errors again 😊
