### ISSUE TITLE
Support for Waveshare NRF51822 Eval Kit

### ISSUE THREAD

**Issue by digitalstreamio** [platformio/platformio#655]
Any thoughts on what it would take to support this nRF51822 based board?

http://www.waveshare.com/product/modules/wireless/bluetooth/nrf51822-eval-kit.htm
http://www.waveshare.com/wiki/NRF51822_Eval_Kit

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-nordicnrf51/issues/4
