### ISSUE TITLE
chipKIT Uno32 build fails under Linux 64-bits

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platformio#657]
Example of failed build job:
https://travis-ci.org/blynkkk/blynk-library/jobs/128466485

**Comment by ivankravets** [comment]
Microchip provides broken toolchain for Linux x64. The temporary solution is to use 32-bit toolchain and install dependent packages. See how we do it for the own tests https://github.com/platformio/platformio/blob/develop/.travis.yml#L14

This is a temporary solution.

**Comment by ivankravets** [comment]
Please try new Microchip PIC32 development version with updated toolchain and tools.

Also, don't forget to add to travis.yaml config `sudo apt-get install libc6-i386`.  See http://chipkit.net/wiki/index.php?title=ChipKIT_core#64-Bit_Linux
