### ISSUE TITLE
lightblue-bean build fails

### ISSUE THREAD

**Issue by vshymanskyy** [platformio/platformio#658]
Example of failed build job:
https://travis-ci.org/blynkkk/blynk-library/jobs/129172821

**Comment by valeros** [comment]
Hi @vshymanskyy 
Does `examples/More/LightBlueBeanRGB` project exist in your repo?
Looks like this example is relocated here `examples/BoardsAndShields_Bluetooth/LightBlueBean_BLE`

**Comment by vshymanskyy** [comment]
Sorry for wasting your time, completely my fault. Overlooked a line in auto-generator script.
Keep-up the good work!
