### ISSUE TITLE
Missing deb-package dependency: python-requests

### ISSUE THREAD

**Issue by dothebart** [platformio/platformio#660]
- [x ] Bug report. If you’ve found a bug, please provide information below.

Downloaded & installed the .deb file; platformio wouldn't start because of the module `request` missing.

    apt-get install python-request 

fixed the issue.
So, the .deb should depend on this package.

**Comment by ivankravets** [comment]
How did you install `platformio`?

**Comment by dothebart** [comment]
I downloaded the .deb via the download link, and `dpkg -i platformio-atom-linux-x86_64.deb`ed it.

**Comment by ivankravets** [comment]
Hm... In this case, PlatformIO IDE installs own version of PlatformIO CLI and creates special Python environment.

Do you have PlatformIO CLI globally installed in your system?

**Comment by dothebart** [comment]
yes, installed the .deb as root. Its living in /usr/local.

**Comment by ivankravets** [comment]
Please provide me an output of `which pio`. Thanks.

**Comment by ivankravets** [comment]
Please reopen if you still need help

**Comment by dothebart** [comment]
sorry, I didn't need help. I fixed it for myself by installing the missing dependency. This issue was about you fixing it for other users that may run into this trap.

**Comment by ivankravets** [comment]
@dothebart Thanks a lot for the report!
