### ISSUE TITLE
Minor issue: compile time symbol redefinition

### ISSUE THREAD

**Issue by malachib** [platformio/platformio#667]
This hasn't been stopping me, but looks like it might cause a problem for someone at some point.

During compilation of SAMD+Arduino (Arduino Zero compatible) code, we repeatedly get the warning:

<command-line>:0:0: warning: "USB_MANUFACTURER" redefined [enabled by default]

Because:

`arm-none-eabi-g++ -DUSB_MANUFACTURER=\"Arduino\"  -DUSB_MANUFACTURER="PlatformIO"`

is happening

**Comment by ivankravets** [comment]
Fixed in PlatformIO 3.0. I'm going to make it public next week.
