### ISSUE TITLE
Upload to target eventually fails after multiple uploads due to "no space left on device"

### ISSUE THREAD

**Issue by gilandose** [platformio/platformio#669]
### Configuration

**Operating system**:  Linux

**PlatformIO Version** (`platformio --version`):PlatformIO, version 2.9.1
### Description of problem

```
[Tue May 24 16:13:58 2016] Processing nucleo_f401re (platform: ststm32, upload_port: /media/rgilmore/NODE_F401RE, board: nucleo_f401re, framework: mbed, bui
ld_flags: -lstdc++ -lsupc++)
--------------------------------------------------------------------------------
MethodWrapper(["upload"], [".pioenvs/nucleo_f401re/firmware.bin"])
scons: *** [upload] No space left on device
========================= [ ERROR ] Took 1.13 seconds =========================
```
#### Steps to Reproduce

1.Upload a design to device multiple times.
2.After a certain number of times error appears
3.unplug and replug in device to fix
### Actual Results

Seems to keep incrementing write area until no space left
### Expected Results

Should erase flash and upload new program.
### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**

```

[env:nucleo_f401re]
platform = ststm32
framework = mbed
board = nucleo_f401re
build_flags = -lstdc++ -lsupc++
upload_port=/media/rgilmore/NODE_F401RE
```

**Comment by valeros** [comment]
Hi @gilandose, sorry for the late reply! Our uploader just copies a firmware to `mbed` media disk and nothing more, so probably the problem isn't in PlatformIO.
As I know `nucleo_f401re` has the embedded `st-link` programmer on the board. Have you considered using `tool-stlink` as an alternative uploader?
```
[env:nucleo_f401re]
platform = ststm32
framework = mbed
board = nucleo_f401re
upload_protocol = stlink
```

**Comment by ivankravets** [comment]
Moved to https://github.com/platformio/platform-ststm32/issues/23
