### ISSUE TITLE
Feature Request - ARM tool-openocd

### ISSUE THREAD

**Issue by marty-sullivan** [platformio/platformio#674]
When I try to upload to my Due from Raspberry Pi I get the message "Error: The package 'tool-openocd' is not available for your system 'linux_armv7l'"

How do I either install this manually or can you guys add the package to your repo?

**Comment by ivankravets** [comment]
We don't have binaries for Linux ARM. See full list https://bintray.com/platformio/dl-packages/tool-openocd/view#files

Could you provide us OpenOCD binaries?

**Comment by marty-sullivan** [comment]
Sure, I could do that. Is there a specific way things need to be packaged? Or just regular build directory is fine?

**Comment by ivankravets** [comment]
Take a look at these examples https://bintray.com/platformio/dl-packages/tool-openocd/view#files

**Comment by marty-sullivan** [comment]
So I've built the package, but I notice that each package has a "bin/openocd.bin" but I don't know what this is or how to make it. Probably just my unfamiliarity with the platform.

**Comment by ivankravets** [comment]
Please archive it and share somewhere. I'll take a look.

**Comment by marty-sullivan** [comment]
Here is the package so far:

https://cornell.box.com/s/s8rflgdvo6kmnd1zdoebf5xhy12u6r6e

**Comment by ivankravets** [comment]
It requires login/pass. Please attach archive here.

**Comment by marty-sullivan** [comment]
sorry i forgot to edit the permissions, should work now. I'm on the road so I can't attach it atm. Thanks

**Comment by ivankravets** [comment]
Thanks. I've just added this package to the repo. Please test.

**Comment by marty-sullivan** [comment]
OK, looks like all is good. Thanks for the quick help.

**Comment by ivankravets** [comment]
Happy Coding with PlatformIO! 😊
