### ISSUE TITLE
Specifying "-Lsomelocaldir" as a build option fails

### ISSUE THREAD

**Issue by lerneaenhydra** [platformio/platformio#688]
### Configuration

**Operating system**: Linux 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:15 UTC 2016 i686 athlon i686 GNU/Linux

**PlatformIO Version** (`platformio --version`): PlatformIO, version 2.9.1

### Description of problem
Assuming some directory 'foo' exists in the project root then specifying "-Lfoo" in the build_flags section of a platformio.ini file actually results in "-Lscripts/foo" being sent to the linker.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
#
# Project Configuration File
#
# A detailed documentation with the EXAMPLES is located here:
# http://docs.platformio.org/en/latest/projectconf.html
#

# A sign `#` at the beginning of the line indicates a comment
# Comment lines are ignored.

# Simple and base environment
# [env:mybaseenv]
# platform = %INSTALLED_PLATFORM_NAME_HERE%
# framework =
# board =
#
# Automatic targets - enable auto-uploading
# targets = upload

[env:disco_f407vg]
platform = ststm32
framework = spl
board = disco_f407vg
build_flags = -lPDMFilter_GCC -Llib_ext
```

**Comment by ivankravets** [comment]
Please test it with the latest http://docs.platformio.org/en/latest/installation.html#development-version
