### ISSUE TITLE
Path to "platformio"?

### ISSUE THREAD

**Issue by tahiro86j** [platformio/platformio#690]
- [ ] Bug report. If you’ve found a bug, please provide information below.

### Configuration

**Operating system**:"Windows 10"

**PlatformIO Version** (`platformio --version`):IDE 1.2.2 | CLI 2.9.4

### Description of problem
Command "platformio" cannot be found.

#### Steps to Reproduce

1.platformio-atom-windows.exe installation
2. Win+R -> cmd.exe -> platformio -> (won't run, says the command cannot be found. "where platformio" was of no luck.)

### Additional info
None

**Comment by ivankravets** [comment]
PlatformIO IDE contains built-in PlatformIO CLI that is not installed globally. Please use PlatformIO Terminal to access CLI or install shell commands globally. See PlatformIO IDE `Menu: PlatformIO > Install Shell Commands`.

**Comment by tahiro86j** [comment]
Thx.
