### ISSUE TITLE
Shell Commands not installed Win 10

### ISSUE THREAD

**Issue by DIYElectronicsZA** [platformio/platformio#703]
### Configuration

**Windows 10 x64**:

**2.10.3** (`platformio --version`):

### Description of problem
Shell commands for platformio not installed under Windows 10 x64 after installing PlatformIO IDE. Tried "Menu > PlatformIO > Install Shell Commands " Multiple times with no luck. No response from IDE whatsoever when clicking install shell commands. 
Tried on two different machines, same problem. 

#### Steps to Reproduce

1.Install PlatformIO IDE
2.'Install Shell Commands'
3.cmd.exe > platformio : 'platformio' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ivankravets** [comment]
This issue is related to PlatformIO IDE. Please move it to https://github.com/platformio/platformio-atom-ide/issues
