### ISSUE TITLE
Dynamic variables/templates for use in platformio.ini

### ISSUE THREAD

**Issue by sticilface** [platformio/platformio#705]
I'd like to define some variables that are constant between about 6 [env].  is this possible... 

something like 

```
[platformio]
src_dir = ./MyMelvanimate ; keeps arduino happy :)
data_dir = ./MyMelvanimate/data
env_default = esp12e-debug
test_var='-lstdc++ -Wl,-Tesp8266.flash.4m.ld -lc -I"/Users/amelvin/Arduino/esp8266/tools/sdk/libc/xtensa-lx106-elf/include" -L"/Users/amelvin/Arduino/esp8266/tools/sdk/libc/xtensa-lx106-elf/lib"'
```

then later
```
[env:debug]
platform = espressif
framework = arduino
board = esp12e
;build_flags = -lstdc++ -Wl,-Tesp8266.flash.4m.ld -lc -I"/Users/amelvin/Arduino/esp8266/tools/sdk/libc/xtensa-lx106-elf/include" -L"/Users/amelvin/Arduino/esp8266/tools/sdk/libc/xtensa-lx106-elf/lib" ;   -DDebug_ESPManager -DDEBUG_ESP_PORT=Serial -DDebugUDP ; -DDebugMelvanimate ;-DDEBUG_ESP_CORE -DDEBUG_ESP_WIFI
build_flags = $test_var; -lstdc++ -Wl,-Tesp8266.flash.4m.ld
board_flash_mode = qio
board_f_cpu = 160000000L
board_f_flash = 80000000L
lib_install = 13, 547, 89 ; 64 = arduinojson
upload_port = 192.168.1.70 ; nodemcu
```

**Comment by sticilface** [comment]
thats great cheers.  Was a question so moved it to the forum.

**Comment by ivankravets** [comment]
Why did you close this issue? That is a great feature for PaltformIO 3.0. I had the same idea 👍 

Now, it should be 100% implemented.

**Comment by ivankravets** [comment]
Python support variables by default https://docs.python.org/2/library/configparser.html but only for the vars inside environment.

How about to keep Python syntax and extend this format?

```ini
[someenv]
var1 = hello
var2 = %(var1) world  ; Python understands this

[env:myenv]
test = %(someenv.var2)  ; Python doesn't understand this but we will emulate

```

**Comment by sticilface** [comment]
This looks great:)

**Comment by itsjustvenky** [comment]
Yes.. this is really a nice idea.a great feature indeed

**Comment by ivankravets** [comment]
Please re-test it with the latest development version http://docs.platformio.org/en/latest/installation.html#development-version

Docs: http://docs.platformio.org/en/latest/projectconf.html

**Comment by raymusmunt** [comment]
Works great @ivankravets

**Comment by ivankravets** [comment]
@raymusmunt please give us a 🌟 https://github.com/platformio/platformio/stargazers 😊
