### ISSUE TITLE
Misplaced header files in Qt creator project file

### ISSUE THREAD

**Issue by viktor-irafm** [platformio/platformio#713]
### Configuration

**Operating system**:
linux amd64

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 2.11.1.dev0

### Description of problem

When used command: `platformio init --ide qtcreator --board uno` for generating files for Qt creator IDE if header files are in the src directory they are added into SOURCES variable in the resulting platformio.pro file but they should be added into HEADERS variable.

#### Steps to Reproduce

1. place header files into src directory
2. execute `platformio init --ide qtcreator --board uno`

### Actual Results

```
SOURCES += src/main.cpp
SOURCES += src/file2.cpp
SOURCES += src/file2.h
SOURCES += src/main.h
```

### Expected Results

```
SOURCES += src/main.cpp
SOURCES += src/file2.cpp

HEADERS += src/main.h
HEADERS += src/file2.h
```

**Comment by ivankravets** [comment]
Please retest with http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by viktor-irafm** [comment]
Yes! I may confirm it works, thanks.
