### ISSUE TITLE
Request: Arduino ISP Support

### ISSUE THREAD

**Issue by sergiotomasello** [platformio/platformio#717]
Could you add support to [Arduino ISP](http://www.arduino.org/products/shields/arduino-isp) by Arduino Srl? 

Following the lines to be included into `avrdude.conf` file:

```
programmer
id    = "arduinoisporg";
desc  = "Arduino ISP Programmer";
type  = "usbtiny";
connection_type = usb;
usbvid     = 0x2A03;
usbpid     = 0x0049;
;
```

Regards
Sergio

**Comment by valeros** [comment]
Thanks, updated!

**Comment by tiborebner** [comment]
I still don't see the entry with `id = arduinoisporg` in my PlatformIO-specific `avrdude.conf`. What happened to that? I had to put it in there manually for it to work with my ISP programmer.

**Comment by ivankravets** [comment]
@tiborebner Please file new issue here https://github.com/platformio/platform-atmelavr/issues

**Comment by ivankravets** [comment]
@tiborebner Please run `pio update`, the `avrdude` package was updated. Thanks.
