### ISSUE TITLE
samd21_xpro

### ISSUE THREAD

**Issue by alexptbg** [platformio/platformio#720]
Hi,
I am running the latest versions of all software (win10 pro+Atom+platform+python2.7)
Everything work fine when using with arduino avr boards.
When i try to build for samd21 xpro board i have the this error:

platformio.ini

[env:samd21_xpro]
platform = atmelsam
framework = mbed
board = samd21_xpro

src\main.cpp

#include "Arduino.h"

void setup() {
  pinMode(LED_BUILTIN, OUTPUT);
}

void loop() {
  digitalWrite(LED_BUILTIN, HIGH);
  delay(1000);
  digitalWrite(LED_BUILTIN, LOW);
  delay(1000);
}

error:

platformio run --target upload
src\main.cpp:6:21: fatal error: Arduino.h: No such file or directory
#include "Arduino.h"
^
compilation terminated.
scons: *** [.pioenvs\samd21_xpro\src\main.o] Error 1
[ ERROR ] Took 1.26 seconds

Now if the code is clean without the include i got another error:

 main.cpp
 
void setup() {
 
}
 
void loop() {
 
}

platformio run
[07/13/16 12:50:25] Processing samd21_xpro (platform: atmelsam, board: samd21_xpro, framework: mbed)
 
arm-none-eabi-g++ -o .pioenvs\samd21_xpro\firmware.elf -Wl,--gc-sections -Wl,--wrap,main -mcpu=cortex-m0plus -mthumb --specs=nano.specs -Wl,-T"C:\Users\Alex\.platformio\packages\fra
mework-mbed\variant\SAMD21J18A\mbed\TARGET_SAMD21J18A\TOOLCHAIN_GCC_ARM\samd21j18a.ld" .pioenvs\samd21_xpro\src\main.o -LC:\Users\Alex\.platformio\packages\ldscripts -LC:\Users\Alex
\.platformio\packages\framework-mbed\variant\SAMD21J18A\mbed\TARGET_SAMD21J18A\TOOLCHAIN_GCC_ARM -L.pioenvs\samd21_xpro -Wl,--start-group -Wl,-whole-archive .pioenvs\samd21_xpro\lib
FrameworkMbed.a -Wl,-no-whole-archive -lstdc++ -lsupc++ -lnosys -lmbed -lc -lgcc -lc -lgcc -lm -Wl,--end-group

.pioenvs\samd21_xpro\libFrameworkMbed.a(retarget.o): In function `__wrap_main':

retarget.cpp:(.text.__wrap_main+0xa): undefined reference to `main'
collect2.exe: error: ld returned 1 exit status
scons: *** [.pioenvs\samd21_xpro\firmware.elf] Error 1
 [ ERROR ] Took 1.30 seconds

Can someone help me here?

Thanks in advance,

Alex Soares

**Comment by ivankravets** [comment]
You are going to build Arduino code using `mbed` framework. That is not possible.

You should use `mbed` framework for that. See examples https://github.com/platformio/platformio-examples/tree/develop/mbed
