### ISSUE TITLE
Cannot build Teensy20 project with USB Type: "MIDI"

### ISSUE THREAD

**Issue by venelinpetrov** [platformio/platformio#722]
### Configuration

**Operating system**:
Windows 7 Professional

**PlatformIO Version**:
2.11.1
### Description of problem
The ```build_flags = -USB_MIDI``` flag does not seem to take effect, because midi specific methods are not recognized during compilation (e.g. ```usbMIDI.sendControlChange();```)

### Steps to reproduce:

1. Initialize teensy20 project. You should have the following config:

  ```ini
[env:teensy20]
platform = teensy
framework = arduino
board = teensy20
```
2. Add this entry to platformio.ini

  ```ini
build_flags = -USB_MIDI
# or build_flags = -DUSB_MIDI
```
3. Execute

  ```
pio run
```

### Actual Results
Exception is thrown saying that ```usbMIDI``` is not recognized

### Expected Results
Successful compilation

**Comment by ivankravets** [comment]
@valeros please re-assign this issue to me when will fix it. I'll add this info to docs.

**Comment by ivankravets** [comment]
Docs: http://docs.platformio.org/en/latest/platforms/teensy.html#teensy-2-0-and-usb

**Comment by venelinpetrov** [comment]
Just to avoid any misunderstanding I would like to underline that the problem (and the fix also) does not seem to depend on the teensy board version. I tested it now with teensy 3.0 project and the behavior is the exact same. You can unmention the version in the documentation if you like.

**Comment by ivankravets** [comment]
Thanks a lot! I've just updated the docs.

P.S: Does this build work with Teensy 2.0?

**Comment by venelinpetrov** [comment]
Yes, testing with the latest development version, the code compiles and uploads successfully to a physical board. Also needed to add the ```build_flags = -D USB_MIDI``` entry as the documentation suggests.
Thanks for the effort, really. Actually, I came up with a similar solution today, but couldn't find time to dig enough in the code in order to verify it.

**Comment by ivankravets** [comment]
Thank you, that reported!

Happy coding! 😊
