### ISSUE TITLE
Typo on microchippic32.json file

### ISSUE THREAD

**Issue by hormigaAzul** [platformio/platformio#725]
What kind of issue is this?

- [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
      something, or to understand why something isn't working the way you expect it to, use
      our Community Forums https://community.platformio.org

- [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
      already exists! Don’t send pull requests to implement new features without first getting our
      support. Sometimes we leave features out on purpose to keep the project small.

- [ ] PlatformIO IDE. All issues related to PlatformIO IDE should be reported to appropriate repository
      https://github.com/platformio/platformio-atom-ide/issues

- [X ] Bug report. If you’ve found a bug, please provide information below.

*You can erase any parts of this template not applicable to your Issue.*

------------------------------------------------------------------

### Description of problem

There is a typo error on line 122 of the microchippic32.json file. Where it says **cchipKIT-application-32MX250F128.ld** it should say **chipKIT-application-32MX250F128.ld** This prevents compilation on the chipKit-pi board.

#### Steps to Reproduce

1. Try to compile anything for the chipkit-pi

### Actual Results

[07/18/16 12:16:14] Processing chipkit_pi (platform: microchippic32, board: chipkit_pi, framework: arduino)

pic32-g++ -o .pioenvs\chipkit_pi\firmware.elf -w -Os -mdebugger -mprocessor=32MX250F128B -mno-peripheral-libs -nostartfiles -Wl,--gc-sections -Wl,--script="cchipKIT-application-32MX250F128.ld" -Wl,--script=chipKIT-application-COMMON.ld .pioenvs\chipkit_pi\src\tmp_ino_to.o "-LC:\Users\Maker I\.platformio\packages\framework-arduinomicrochippic32\cores\pic32" "-LC:\Users\Maker I\.platformio\packages\framework-arduinomicrochippic32\variants\ChipKIT_Pi" "-LC:\Users\Maker I\.platformio\packages\ldscripts" -L.pioenvs\chipkit_pi -Wl,--start-group .pioenvs\chipkit_pi\libFrameworkArduinoVariant.a .pioenvs\chipkit_pi\libFrameworkArduino.a -lm .pioenvs\chipkit_pi\libSoftwareSerial.a .pioenvs\chipkit_pi\libAdafruit_VC0706.a .pioenvs\chipkit_pi\libSPI.a .pioenvs\chipkit_pi\libSD.a -Wl,--end-group
pic32-cpp.exe: error: cchipKIT-application-32MX250F128.ld: No such file or directory
pic32-cpp.exe: warning: '-x c' after last input file has no effect
pic32-cpp.exe: fatal error: no input files
compilation terminated.
c:\users\maker i\.platformio\packages\toolchain-microchippic32\bin\bin\gcc\pic32mx\4.8.3\..\..\..\..\bin/pic32-ld.exe: cannot open linker script file cchipKIT-application-32MX250F128.ld.00: No such file or directory
collect2.exe: error: ld returned 255 exit status
scons: *** [.pioenvs\chipkit_pi\firmware.elf] Error 255
 [ ERROR ] Took 6.16 seconds 

### Expected Results

Compiled file

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
[env:chipkit_pi]
platform = microchippic32
framework = arduino
board = chipkit_pi
```

**Comment by ivankravets** [comment]
Thanks a lot for the report!
