### ISSUE TITLE
Update to Atmel AVR toolchain and avrdude

### ISSUE THREAD

**Issue by zgoda** [platformio/platformio#735]
Atmel AVR toolchain and avrdude have been recently updated with release of Arduino 1.6.10

**Comment by ivankravets** [comment]
Please move this issue to appropriate repository https://github.com/platformio/platform-atmelavr/issues. Thanks.

**Comment by zgoda** [comment]
Sorry, I had an impression this repo is for upcoming pio v.3. Will report there.
