### ISSUE TITLE
Arduino .ino, Line number problem

### ISSUE THREAD

**Issue by nyuszis** [platformio/platformio#742]
### Configuration

windows 7 64bit

**PlatformIO Version** (`platformio --version`):
PlatformIO, version 2.11.2

### Description of problem
Wrong line number for build ino file

#### Steps to Reproduce

1. write sample ino file and insert \#warning "Line number"
2. build IDE or CLI

![line_problem](https://cloud.githubusercontent.com/assets/10277643/17462369/d7c739a6-5caa-11e6-86f1-18016747dc53.png)

**Comment by ivankravets** [comment]
Please re-test with http://docs.platformio.org/en/stable/installation.html#development-version
