### ISSUE TITLE
Need to use full library paths instead of relative folder paths

### ISSUE THREAD

**Issue by ChrisAlphabet** [platformio/platformio#749]
### Configuration

**Operating system**: Windows 10

**PlatformIO Version** : 3.0.0a4

### Description of problem
When migrating from PIO2 to PIO3 you need to specify the full path to library folders and cannot use relative folder paths in `platformio.ini`

For example, on PIO2 use:

`[env:mybaseenv]`
`lib_dir = ../../MyLibrary`

but on PIO3 this doesn't work. 

Instead you have to use:

`[env:mybaseenv]`
`lib_extra_dirs = C:/full/path/to/MyLibrary`

Note: Must use `lib_extra_dirs` instead of `lib_dir`

Cheers!

**Comment by ivankravets** [comment]
Please `pio upgrade` to 3.0.0a5
