### ISSUE TITLE
Update framework-arduinoteensy

### ISSUE THREAD

**Issue by blackketter** [platformio/platformio#758]
Teensyduino has been updated to 1.29:

https://github.com/PaulStoffregen/cores/tree/1.29

Thanks!

**Comment by ivankravets** [comment]
Thanks a lot for the issue! Please move it to https://github.com/platformio/platform-teensy

This repository is intended for PlatformIO Core.

**Comment by blackketter** [comment]
Done: https://github.com/platformio/platform-teensy/issues/2

**Comment by ivankravets** [comment]
Thanks! 👍
