### ISSUE TITLE
platformio not compile MySensors 2.0

### ISSUE THREAD

**Issue by STASIUK** [platformio/platformio#761]
Not compiled standard examples.
What is the problem?

**Comment by ivankravets** [comment]
PlatformIO 2.0 Build System is not compatible with MySensor 2.0.

See https://forum.mysensors.org/topic/1369/best-ide-to-use-for-mysensors-projects/24

Please switch to PlatformIO 3.0 http://docs.platformio.org/en/stable/installation.html#development-version
