### ISSUE TITLE
Cannot compile nodemcuv2 using version 3.0 

### ISSUE THREAD

**Issue by deladriere** [platformio/platformio#763]
Compilation gives this error 
`sh: -c: line 0: syntax error near unexpected token `('`

reverting to 2.11.2 solve this problem

**Comment by ivankravets** [comment]
Thanks! Fixed in https://github.com/platformio/platformio/commit/0751c966c429c90469e72497ffa909d755411951

Please `pio upgrade` to the latest version.

**Comment by deladriere** [comment]
working in version 3.0.0a10 !
thx
