### ISSUE TITLE
if I comment on the braces, they are still counted

### ISSUE THREAD

**Issue by jourjine** [platformio/platformio#766]
**Operating system**:
Mac OS X 10.11.6
**PlatformIO Version** (`platformio --version`):
2.11.2
### Description of problem
in CPP and INO files
if I comment on the braces, they are still counted in syntax helpers, but no build error

**Comment by ivankravets** [comment]
Please provide source code to reproduce.

**Comment by jourjine** [comment]
```
BLYNK_CONNECTED() {
  if (isFirstConnect) {                 
    Blynk.syncAll();                   
    isFirstConnect = false;             
  } 
}

```

```
BLYNK_CONNECTED() {
  //if (isFirstConnect) {      **<- to this**           
    Blynk.syncAll();                   
    isFirstConnect = false;             
  } **<- on mouse over this bracer still connected **  
}
```

**Comment by jourjine** [comment]
```
BLYNK_CONNECTED() {
  //if (isFirstConnect) {   <- to this              
  if (isFirstConnect) {                 
    Blynk.syncAll();                   
    isFirstConnect = false;             
  }
} <- this
```

highlight mistake

**Comment by ivankravets** [comment]
You comment 1 line... What is wrong?

**Comment by jourjine** [comment]
![image](https://cloud.githubusercontent.com/assets/774345/18070445/8c8d8068-6e56-11e6-983d-e7b1a3b68cd9.png)
![image](https://cloud.githubusercontent.com/assets/774345/18070451/9c075f14-6e56-11e6-9942-a9c185806277.png)

**Comment by jourjine** [comment]
![image](https://cloud.githubusercontent.com/assets/774345/18070496/d650fc3e-6e56-11e6-8bd9-00b0730e1bcc.png)
![image](https://cloud.githubusercontent.com/assets/774345/18070498/dc6486ea-6e56-11e6-85f7-08b8e92a1962.png)

**Comment by ivankravets** [comment]
Pleas move your issue here https://github.com/atom/language-c/issues
