### ISSUE TITLE
Cannot compile nodemcuv2 using version 3.0.0.b13

### ISSUE THREAD

**Issue by deladriere** [platformio/platformio#770]
gives this error

collect2: error: ld returned 1 exit status
*** [.pioenvs/nodemcuv2/firmware.elf] Error 1

reverting to 2.11.2 works

**Comment by ivankravets** [comment]
How to reproduce this issue? Could you provide test `platformio.ini` and source code?

**Comment by deladriere** [comment]
Here is the complete folder

[Blynk.zip](https://github.com/platformio/platformio/files/456391/Blynk.zip)

**Comment by deladriere** [comment]
[Blynk.zip](https://github.com/platformio/platformio/files/456395/Blynk.zip)
here is the folder

**Comment by deladriere** [comment]
[Blynk.zip](https://github.com/platformio/platformio/files/456400/Blynk.zip)

**Comment by ivankravets** [comment]
I've just tried your project and don't see any problems

# platformio.ini

```ini
[env:nodemcuv2]
platform = espressif8266
framework = arduino
board = nodemcuv2
lib_deps = Blynk, SimpleTimer, DallasTemperature, Encoder
```

See output http://pastebin.com/Qs064aru

**Comment by deladriere** [comment]
added lib_deps = Blynk, SimpleTimer, DallasTemperature, Encoder
to platformio.ini solved it !
very strange

**Comment by ivankravets** [comment]
You are going to use a few external libraries in your project and you don't have them. The code could not be built.

**Comment by deladriere** [comment]
I does compile fine under 2.11.2

**Comment by deladriere** [comment]
now I have a new error
Exception OSError: OSError(2, 'No such file or directory') in <bound method dblite.__del__ of <SCons.dblite.dblite obje
ct at 0x10586f150>> ignored
if I keep ib_deps = Blynk, SimpleTimer, DallasTemperature, Encoder
removed it and now compiles fine  !!!

**Comment by deladriere** [comment]
sorry cannot reproduce Exception OSError: OSError(2, 'No such file or directory') in ct at 0x10586f150>> ignored

**Comment by ivankravets** [comment]
I don't know what do you do. Try to clean project via `pio run -t clean`. Now, run it again via `pio run`. Do you see any errors?
