### ISSUE TITLE
[FIXED] SSLError: hostname 'dl.platformio.org' doesn't match 'pioplus.com'

### ISSUE THREAD

**Issue by zouden** [platformio/platformio#774]
# FIXED

Fixed in development version. Please upgrade http://docs.platformio.org/en/stable/installation.html#development-version

-------

### Configuration

**Operating system**: Win10 x64

**PlatformIO Version** 3.0.1

### Description of problem

I get the above error when trying to install a library (Homie).

#### Steps to Reproduce

1. pio lib install homie

### Actual Results

Download fails with that error

### Expected Results

Library should install

**Comment by ivankravets** [comment]
Fixed in development version. Please upgrade http://docs.platformio.org/en/stable/installation.html#development-version

**Comment by zouden** [comment]
Great it works now. Thanks for the extremely fast response!

**Comment by Palatis** [comment]
It didn't work for https://platformio.org either...

I think a better way is to get a proper cert...

**Comment by ivankravets** [comment]
@Palatis we use HTTPS for all our resources except home page (issue with CDN)

**Comment by ivankravets** [comment]
Fixed in PlatformIO 3.1.0
