### ISSUE TITLE
Support for Leaf Labs' Maple/Maple Mini boards

### ISSUE THREAD

**Issue by jasiek** [platformio/platformio#782]
Despite these boards being no longer supported by the manufacturer, there's a significant cache of boards available from China at a very low cost. Perhaps it would be worth adding support for these.

http://www.leaflabs.com/maple

**Comment by ivankravets** [comment]
Please move this issue to appropriate repository https://github.com/platformio/platform-ststm32/issues

P.S: We are working on it. The latest development version of ST STM32 platform has support for Maple board.
