### ISSUE TITLE
Cannot compile Adafruit Adafruit_SSD1306 

### ISSUE THREAD

**Issue by deladriere** [platformio/platformio#783]
using IDE 1.5.0 | CLI 3.0.1
Was compiling fine under version 2
Compiles  fine with Arduino 1.6.11

[env:adafruit_feather_m0_usb]
platform = atmelsam
framework = arduino
board = adafruit_feather_m0_usb

**Comment by deladriere** [comment]
seems that the include are gone 

#include <Arduino.h>
#include <SPI.h>
#include <SD.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

**Comment by ivankravets** [comment]
Please use triple of ``` (in new line, begin and end) for code highlighting

**Comment by deladriere** [comment]
using paste bin : http://pastebin.com/gZ8rr5c2

**Comment by deladriere** [comment]
can you reproduce this issue ?

**Comment by ivankravets** [comment]
Please read about LDF and Dependency Finder Mode http://docs.platformio.org/en/stable/librarymanager/ldf.html#dependency-finder-mode

Adafruit SSD1306 depends on Wire library but doesn't include it directly on header file. You should manually resolve this issue or switch `lib_ldf_mode = 2`. However, I don't recommend to do it.

See other normal solutions:

1. You can manually `#include <Wire.h>` in your project main file.
2. You can ask PlatformIO Library Builder include `Wire` library automatically. See:

```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[env:adafruit_feather_m0_usb]
platform = atmelsam
board = adafruit_feather_m0_usb
framework = arduino
lib_force = Wire
lib_deps = Adafruit SSD1306
```
