### ISSUE TITLE
Installation Python problem

### ISSUE THREAD

**Issue by J2xWo** [platformio/platformio#791]
### Configuration

Windows 10 64bit
PlatformIO Version: 1.10.2

### Description of problem

![error](https://cloud.githubusercontent.com/assets/22383957/18772019/df4d0b98-8143-11e6-80b4-ca320772b6f6.png)

Hello everyone!
Well as soon as i start the installation i get this error after its nearly finished. I reinstalled python, made sure that i select "Add python.exe to path", i deactivated my antivirusprogram, restarted my computer but nothing worked.. Python seems to function, at least when i open cmd and type python in there, it responds.. Had or has someone a similar problem?

**Comment by ivankravets** [comment]
> PlatformIO Version: 1.10.2

What is it?

**Comment by ivankravets** [comment]
Please reopen if you still need help
