### ISSUE TITLE
Support for SODAQ boards

### ISSUE THREAD

**Issue by Roman3349** [platformio/platformio#796]
Can you add support for the SODAQ boards of the Arduino framework?

**Boards with Atmel SAM MCU:**
- [ ]  [SODAQ Autonomo](http://support.sodaq.com/sodaq-one/autonomо/) (ATMEL ATSAMD21J18),
- [ ]  [SODAQ ONE](http://support.sodaq.com/sodaq-one/) (ATMEL ATSAMD21G18).

**Boards with Atmel AVR MCU:**
- [ ]  [SODAQ Mbili](http://support.sodaq.com/sodaq-one/sodaq-mbili-1284p/) (ATMEL ATMEGA1284P),
- [ ]  [SODAQ Moja](http://support.sodaq.com/sodaq-one/moja/) (ATMEL ATMEGA328P).

**Repositories:**
- [Sodaq_boards](https://github.com/SodaqMoja/Sodaq_boards),
- [SodaqCore-avr](https://github.com/SodaqMoja/SodaqCore-avr),
- [SodaqCore-samd](https://github.com/SodaqMoja/SodaqCore-samd).

**Comment by ivankravets** [comment]
Resolved in

* https://github.com/platformio/platform-atmelavr/commit/eedaa7adbd379fd3dd4128fcbc56ed80ab99e34d
* https://github.com/platformio/platform-atmelsam/commit/0a0d554ae5d46fe9f9b517ce78195ef3f098fc45
