### ISSUE TITLE
Verify Failures on AtTiny85

### ISSUE THREAD

**Issue by NormanDunbar** [platformio/platformio#799]
What kind of issue is this?

- [X ] PlatformIO Core. If you’ve found a bug, please provide an information below.
------------------------------------------------------------------

### Configuration

**Operating system**: Linux Mint 18, 64 bit.

**PlatformIO Version** (`platformio --version`): IDE=1.6.0, CLI=3.1.0

### Description of problem
After upgrading to latest PlatformIO, all my AtTiny85 scripts fail to verify. Each is Arduino compatible, and work fine on the Arduino IDE.

#### Steps to Reproduce

1. Compile attached Script.
2. Select Upload (I'm in Atom by the way).
3. Verification fails. Always.

### Actual Results

AtTiny85_Blink
AtTiny85_Blink
lib
.gitignore
.travis.yml
platformio.ini
untitled
PlatformIO Home

Welcome to PlatformIO

IDE 1.6.0 | CLI 3.1.0 

Quick access

New Project
Import Arduino Project
Open Project
Project Examples
 Plus ·  Home ·  Get Started ·  Docs ·  Community ·  Report Issue
Recent projects

AtTiny85_Blink
/home/norman/Dropbox_2/Dropbox/Arduino/AtTiny85_Blink
PlatformIO
/home/norman/SourceCode/PlatformIO
AtTiny85_INT0
/home/norman/Dropbox_2/Dropbox/Arduino/AtTiny85_INT0
tmp
/tmp
attiny_blink
/home/norman/Arduino/attiny_blink
Show PlatformIO Home screen on startup
 with  by PlatformIO Plus
2.8 s
platformio run --target upload
avrdude: verification error; content mismatch
 
 
avrdude done.  Thank you.
*** [upload] Error 1
========================== [ERROR] Took 2.69 seconds ==========================
 

[AtTiny85_Blink.zip](https://github.com/platformio/platformio/files/505048/AtTiny85_Blink.zip)

### Expected Results
Verification to pass. As it does when compiled and uploaded (using programmer) from the Arduino IDE.

### If problems with PlatformIO Build System:

**The content of `platformio.ini`:**
```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[env:attiny85]
platform=atmelavr
board=attiny85
framework=arduino

[platformio]
src_dir=AtTiny85_Blink

```

**Source file to reproduce issue:**
```cpp
#include <Arduino.h>

/*
  Blink
  Turns on an LED on for one second, then off for one second, repeatedly.

  Most Arduinos have an on-board LED you can control. On the Uno and
  Leonardo, it is attached to digital pin 13. If you're unsure what
  pin the on-board LED is connected to on your Arduino model, check
  the documentation at http://www.arduino.cc

  This example code is in the public domain.

  modified 8 May 2014
  by Scott Fitzgerald
 */

const int LED = 0;  // Which pin is the LED on?

// the setup function runs once when you press reset or power the board
void setup() {
  // initialize digital pin 13 as an output.
  pinMode(LED, OUTPUT);
}

// the loop function runs over and over again forever
void loop() {
  digitalWrite(LED, HIGH);   // turn the LED on (HIGH is the voltage level)
  delay(1000);              // wait for a second
  digitalWrite(LED, LOW);    // turn the LED off by making the voltage LOW
  delay(1000);              // wait for a second
}

```

### Additional info

I have uploaded my entire test project as an attached zip file.

I am using a USBTiny programmer as opposed to the USB and a boot loader. I use this all the time whether in PlatformIO or Arduino.

I'm currently unable to upload any code to my AtTiny85 microcontrollers from within Atom/PlatformIO at the moment. 

I have tested the problem on 10 different AtTiny85s, none work. All word from within the Arduino IDE.

Cheers.

**Comment by ivankravets** [comment]
1. You need to use `Program` instead `Upload`
2. Check docs for extra options when using external prgorammer http://docs.platformio.org/en/stable/platforms/atmelavr.html#upload-using-programmer
