### ISSUE TITLE
Could you support Pololu's Astar32U4

### ISSUE THREAD

**Issue by crazyquark** [platformio/platformio#804]
These are the boards:
[AStar32U4 Boards](https://www.pololu.com/category/149/a-star-programmable-controllers)

And the code:
[AStar32U4](https://github.com/pololu/a-star-32u4-arduino-library)

**Comment by ivankravets** [comment]
The library is added http://platformio.org/lib/show/622/AStar32U4

Please use temporary Arduino Leonardo (`leonardo`) board configuratrion. They are the same.

**Comment by crazyquark** [comment]
I did do that however I can't figure out how to set the board's USB to act as a keyboard?
In Arduino IDE this was by default.

**Comment by crazyquark** [comment]
Using build_flags = -DUSB_SERIAL_HID or -DUSB_HID seems to have no effect on this board.

**Comment by ivankravets** [comment]
The repo is created. Please make PR to it.

https://github.com/platformio/platformio-pkg-framework-arduinoavr

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-atmelavr/commit/5af0f34c89a1a23b5b36f9411a18d61665c24da4
