### ISSUE TITLE
For Leonardo boards: how to enable USB HID behavior?

### ISSUE THREAD

**Issue by crazyquark** [platformio/platformio#811]
I tried using -DUSB_HID and -DUSB_SERIAL_HID in the build_flags section but it hasn't worked:
[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
build_flags = -DUSB_SERIAL_HID

My board is an Astar32u4(from Pololu)

The same code works fine with the Arduino IDE

**Comment by ivankravets** [comment]
Please go to Arduino IDE settings and enable verbose output for building and uploading.
Then build project in Arduino IDE and share an output on http://pastebin.com

**Comment by crazyquark** [comment]
Here is the compile output:
http://pastebin.com/pdMqWy6B

And the upload output:
http://pastebin.com/PLRuXeDt

**Comment by ivankravets** [comment]
Try to add these macros
```ini
[env:leonardo]
platform = atmelavr
board = leonardo
framework = arduino
build_flags = -DARDUINO_AVR_A_STAR_32U4 -DUSB_VID=0x1ffb -DUSB_PID=0x2300 -DUSB_MANUFACTURER="Pololu Corporation" -DUSB_PRODUCT="Pololu A-Star 32U4"
```

Check PIO build output that flags are set properly via `pio run --verbose`.

**Comment by crazyquark** [comment]
Unfortunately that had no effect.
The device is recognized in the Device Manager as "Arduino leonardo bootloader", so only serial communication is possible.

**Comment by ivankravets** [comment]
Fixed in https://github.com/platformio/platform-atmelavr/commit/5af0f34c89a1a23b5b36f9411a18d61665c24da4
