### ISSUE TITLE
emitter.prependListener is not a function

### ISSUE THREAD

**Issue by raquena** [platformio/platformio#827]
**Operating system**:
Windows 8.1

**PlatformIO Version** (`platformio --version`):
1.12.2

### Description of problem
The terminal hangs out after the first compilation, it never ends. 
It displays this error message:
emitter.prependListener is not a function.

**Comment by ivankravets** [comment]
See https://community.platformio.org/t/ide-upload-only-works-once-window-counter-doesnt-stop/621/14?u=ivankravets
