### ISSUE TITLE
simulavr and avr-gdb missing from toolchain-atmelavr-linux_x86_64

### ISSUE THREAD

**Issue by HeathPetersen** [platformio/platformio#840]
It appears that simulavr and avr-gdb are missing from toolchain-atmelavr-linux_x86_64.  I believe this is a repeat of bug report #334.  I am new to platformio but am pretty sure this is a  bug and not operator error.

**Comment by ivankravets** [comment]
Please move issue to https://github.com/platformio/platform-atmelavr/issues
